from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

# PATHS
BATTLE_MOVE_ICON_IMG_DIR = 'img/battle/icons/'
BATTLE_MOVE_ICON_GREYSCALE_IMG_DIR = 'img/battle/icons_greyscale/'
BATTLE_MOVE_FRAME_IMG_DIR = 'img/battle/frames/'
BATTLE_MOVE_FRAME_GREYSCALE_IMG_DIR = 'img/battle/frames_greyscale/'
BATTLE_MOVE_GLOW_IMG_DIR = 'img/game_button/glow/'

# BATTLE MOVE ICON DIMENSIONS
BATTLE_MOVE_ICON_WIDTH = int(0.05 * SCREEN_WIDTH)
BATTLE_MOVE_ICON_HEIGHT = int(0.05 * SCREEN_WIDTH)
BATTLE_MOVE_ICON_BIG_WIDTH = int(0.06 * SCREEN_WIDTH)
BATTLE_MOVE_ICON_BIG_HEIGHT = int(0.06 * SCREEN_WIDTH)

# BATTLE MOVE ICON SCALING
BATTLE_MOVE_ICON_BIG_SCALE = 1.2
BATTLE_MOVE_FRAME_SCALE = 1.4

# BATTLE MOVE ICON POSITIONING
BATTLE_MOVE_ICON_DELTA_X = int(0.105 * SCREEN_WIDTH)
BATTLE_MOVE_ICON_DELTA_Y = int(0.16 * SCREEN_HEIGHT)

# BATTLE SHOP SCREEN LAYOUT
BATTLE_SHOP_ICON_START_X = int(0.41 * SCREEN_WIDTH)
BATTLE_SHOP_ICON_START_Y = int(0.22 * SCREEN_HEIGHT)
BATTLE_SHOP_ICONS_PER_ROW = 5

# BATTLE SHOP INFO BOX
BATTLE_SHOP_INFO_BOX_X = int(0.335 * SCREEN_WIDTH)
BATTLE_SHOP_INFO_BOX_Y = int(0.09 * SCREEN_HEIGHT)
BATTLE_SHOP_INFO_BOX_WIDTH = int(0.56 * SCREEN_WIDTH)
BATTLE_SHOP_INFO_BOX_HEIGHT = int(0.57 * SCREEN_HEIGHT)

# BATTLE SHOP INFO BOX SCROLL
BATTLE_SHOP_INFO_BOX_SCROLL_X = int(0.15 * SCREEN_WIDTH)
BATTLE_SHOP_INFO_BOX_SCROLL_Y = int(0.15 * SCREEN_HEIGHT)
BATTLE_SHOP_INFO_BOX_SCROLL_WIDTH = int(0.18 * SCREEN_WIDTH)
BATTLE_SHOP_INFO_BOX_SCROLL_HEIGHT = int(0.44 * SCREEN_HEIGHT)

# SCROLL TEXT POSITIONING
BATTLE_SHOP_SCROLL_TEXT_X = int(0.186 * SCREEN_WIDTH)
BATTLE_SHOP_SCROLL_TEXT_Y = int(0.22 * SCREEN_HEIGHT)

# CONFIRM BUTTON
BATTLE_SHOP_CONFIRM_BUTTON_X = int(0.194 * SCREEN_WIDTH)
BATTLE_SHOP_CONFIRM_BUTTON_Y = int(0.62 * SCREEN_HEIGHT)

# BOUGHT MOVES SLOTS
BATTLE_SHOP_MAX_MOVES = 3
BATTLE_SHOP_SLOT_X = int(0.36 * SCREEN_WIDTH)
BATTLE_SHOP_SLOT_Y = int(0.40 * SCREEN_HEIGHT)
BATTLE_SHOP_SLOT_WIDTH = int(0.06 * SCREEN_WIDTH)
BATTLE_SHOP_SLOT_HEIGHT = int(0.06 * SCREEN_WIDTH)
BATTLE_SHOP_SLOT_DELTA_X = int(0.10 * SCREEN_WIDTH)
BATTLE_SHOP_SLOT_GLOW_WIDTH = int(0.10 * SCREEN_WIDTH)
BATTLE_SHOP_SLOT_FRAME_SCALE = 1.3
BATTLE_SHOP_SLOT_BORDER_COLOR = (140, 90, 45)
BATTLE_SHOP_SLOT_BG_COLOR = (110, 70, 35)
BATTLE_SHOP_SLOT_EMPTY_COLOR = (90, 60, 30)

# FONT SETTINGS
BATTLE_MOVE_ICON_FONT_SIZE = int(0.018 * SCREEN_HEIGHT)
BATTLE_MOVE_ICON_FONT_BIG_SIZE = int(0.022 * SCREEN_HEIGHT)
BATTLE_MOVE_ICON_CAPTION_COLOR = (95, 42, 22)

# GLOW SETTINGS
BATTLE_MOVE_ICON_GLOW_WIDTH = int(0.08 * SCREEN_WIDTH)
BATTLE_MOVE_ICON_GLOW_BIG_WIDTH = int(0.11 * SCREEN_WIDTH)

# BATTLE MOVE TYPE LABEL
BATTLE_SHOP_TYPE_LABEL_FONT_SIZE = int(0.024 * SCREEN_HEIGHT)
BATTLE_SHOP_TYPE_LABEL_COLOR = (95, 42, 22)

# READY BUTTON (battle moves phase — centred below slots)
BATTLE_SHOP_READY_BUTTON_X = int(0.56 * SCREEN_WIDTH)
BATTLE_SHOP_READY_BUTTON_Y = int(0.54 * SCREEN_HEIGHT)

# PHASE BANNER (battle moves mandatory selection notice)
BATTLE_SHOP_PHASE_BANNER_FONT_SIZE = int(0.028 * SCREEN_HEIGHT)
BATTLE_SHOP_PHASE_BANNER_COLOR = (200, 170, 80)
BATTLE_SHOP_PHASE_WAITING_COLOR = (160, 140, 100)
