from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT


# BUILD SCREEN
BUILD_HIERARCHY_IMG_PATH = 'img/figures/build_hierarchy/build_hierarchy.png'
BUILD_HIERARCHY_WIDTH = int(0.452 * SCREEN_WIDTH)
BUILD_HIERARCHY_HEIGHT = int(0.14 * SCREEN_WIDTH)
BUILD_HIERARCHY_X = int(0.39 * SCREEN_WIDTH)
BUILD_HIERARCHY_Y = int(0.27 * SCREEN_HEIGHT)

BUILD_FIGURE_SCROLL_TEXT_X = int(0.186 * SCREEN_WIDTH)
BUILD_FIGURE_SCROLL_TEXT_Y = int(0.22 * SCREEN_HEIGHT)

BUILD_FIGURE_INFO_BOX_X = int(0.335 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_Y = int(0.09 * SCREEN_HEIGHT)
BUILD_FIGURE_INFO_BOX_WIDTH = int(0.56 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_HEIGHT = int(0.57 * SCREEN_HEIGHT)
BUILD_FIGURE_COLOR_BUTTON_X = int(0.154 * SCREEN_WIDTH)
BUILD_FIGURE_COLOR_BUTTON_Y = int(0.09 * SCREEN_HEIGHT)
BUILD_FIGURE_INFO_BOX_SCROLL_X = int(0.15 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_SCROLL_Y = int(0.15 * SCREEN_HEIGHT)
BUILD_FIGURE_INFO_BOX_SCROLL_WIDTH = int(0.18 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_SCROLL_HEIGHT = int(0.44 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT1_X = int(0.18 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT1_Y = int(0.18 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT2_X = int(0.22 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT2_Y = int(0.18 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT3_X = int(0.26 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT3_Y = int(0.18 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT4_X = int(0.30 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT4_Y = int(0.18 * SCREEN_HEIGHT)

BUILD_FIGURE_ICON_WIDTH = int(0.05 * SCREEN_WIDTH)
BUILD_FIGURE_ICON_HEIGHT = int(0.05 * SCREEN_WIDTH)

BUILD_FIGURE_CONFIRM_BUTTON_X = int(0.194 * SCREEN_WIDTH)
BUILD_FIGURE_CONFIRM_BUTTON_Y = int(0.62 * SCREEN_HEIGHT)

# Color button images
BUILD_FIGURE_COLOR_BUTTON_ACTIVE_IMG = 'img/button/confirm/turkis.png'
BUILD_FIGURE_COLOR_BUTTON_INACTIVE_IMG = 'img/button/confirm/turkis_dark.png'








