from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT


# BUILD SCREEN
BUILD_HIERARCHY_IMG_PATH = 'img/figures/build_hierarchy/build_hierarchy.png'
BUILD_HIERARCHY_WIDTH = int(0.452 * SCREEN_WIDTH)
BUILD_HIERARCHY_HEIGHT = int(0.14 * SCREEN_WIDTH)
BUILD_HIERARCHY_X = int(0.38 * SCREEN_WIDTH)
BUILD_HIERARCHY_Y = int(0.29 * SCREEN_HEIGHT)

BUILD_FIGURE_SCROLL_TEXT_X = int(0.16 * SCREEN_WIDTH)
BUILD_FIGURE_SCROLL_TEXT_Y = int(0.36 * SCREEN_HEIGHT)

BUILD_FIGURE_INFO_BOX_X = int(0.33 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_Y = int(0.095 * SCREEN_HEIGHT)
BUILD_FIGURE_INFO_BOX_WIDTH = int(0.545 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_HEIGHT = int(0.616 * SCREEN_HEIGHT)
BUILD_FIGURE_COLOR_BUTTON_X = int(0.14 * SCREEN_WIDTH)
BUILD_FIGURE_COLOR_BUTTON_Y = int(0.13 * SCREEN_HEIGHT)
BUILD_FIGURE_INFO_BOX_SCROLL_X = int(0.125 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_SCROLL_Y = int(0.27 * SCREEN_HEIGHT)
BUILD_FIGURE_INFO_BOX_SCROLL_WIDTH = int(0.2 * SCREEN_WIDTH)
BUILD_FIGURE_INFO_BOX_SCROLL_HEIGHT = int(0.38 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT1_X = int(0.16 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT1_Y = int(0.23 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT2_X = int(0.20 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT2_Y = int(0.23 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT3_X = int(0.25 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT3_Y = int(0.23 * SCREEN_HEIGHT)
BUILD_FIGURE_SUIT4_X = int(0.29 * SCREEN_WIDTH)
BUILD_FIGURE_SUIT4_Y = int(0.23 * SCREEN_HEIGHT)

BUILD_FIGURE_ICON_WIDTH = int(0.04 * SCREEN_WIDTH)
BUILD_FIGURE_ICON_HEIGHT = int(0.04 * SCREEN_WIDTH)










