# Copyright (c) 2026 Marc Stieffenhofer. All rights reserved.
# See LICENSE file in the project root for full license information.
from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT, _FS, _UI_SCALE, _IS_MOBILE
from config.font_settings import FS_BUTTON, FS_BODY, FS_HEADING, FS_SMALL

# BUTTOM
BUTTON_IMG_PATH = 'img/button/'

# MENU BUTTON
MENU_BUTTON_IMG_PATH = 'img/menu_button/menu_button.png'
MENU_BUTTON_GLOW_DIR = 'img/menu_button/glow/'
MENU_BUTTON_WIDTH = int(0.12 * SCREEN_WIDTH)
MENU_BUTTON_HEIGHT = int(0.06 * SCREEN_HEIGHT)

MENU_BUTTON_TEXT_COLOR_HOVERED = (20, 20, 20)
MENU_BUTTON_TEXT_COLOR_ACTIVE = (20, 20, 20)
MENU_BUTTON_TEXT_COLOR_PASSIVE = (240, 240, 240)

# HAND BUTTON
MAIN_HAND_X = int(0.05 * SCREEN_WIDTH)
MAIN_HAND_Y = int(0.8 * SCREEN_HEIGHT)

SIDE_HAND_X = int(0.5 * SCREEN_WIDTH)
SIDE_HAND_Y = int(0.8 * SCREEN_HEIGHT)

BUILD_BUTTON_X = int(0.84 * SCREEN_WIDTH)
BUILD_BUTTON_Y = int(0.86 * SCREEN_HEIGHT)

ACTION_BUTTON_X = int(0.94 * SCREEN_WIDTH)
ACTION_BUTTON_Y = int(0.86 * SCREEN_HEIGHT)

HOME_BUTTON_X = int(0.96 * SCREEN_WIDTH)
HOME_BUTTON_Y = int(0.05 * SCREEN_HEIGHT)

# On mobile, shift the sidebar icons down to make space for a larger home button
_SIDEBAR_Y_OFFSET = int(0.04 * SCREEN_HEIGHT) if _IS_MOBILE else 0

TUTORIAL_BUTTON_X = int(0.96 * SCREEN_WIDTH)
TUTORIAL_BUTTON_Y = int(0.15 * SCREEN_HEIGHT) + _SIDEBAR_Y_OFFSET

LETTER_BUTTON_X = int(0.96 * SCREEN_WIDTH)
LETTER_BUTTON_Y = int(0.27 * SCREEN_HEIGHT) + _SIDEBAR_Y_OFFSET

FIELD_BUTTON_X = int(0.96 * SCREEN_WIDTH)
FIELD_BUTTON_Y = int(0.39 * SCREEN_HEIGHT) + _SIDEBAR_Y_OFFSET

BATTLE_BUTTON_X = int(0.96 * SCREEN_WIDTH)
BATTLE_BUTTON_Y = int(0.51 * SCREEN_HEIGHT) + _SIDEBAR_Y_OFFSET

BATTLE_SHOP_BUTTON_X = int(0.96 * SCREEN_WIDTH)
BATTLE_SHOP_BUTTON_Y = int(0.63 * SCREEN_HEIGHT) + _SIDEBAR_Y_OFFSET



# GAME BUTTON
GAME_BUTTON_SYMBOL_IMG_PATH = 'img/game_button/symbol/'
GAME_BUTTON_GLOW_IMG_PATH = 'img/game_button/glow/'
GAME_BUTTON_GLOW_RECT_IMG_PATH = 'img/game_button/glow_rect/'
GAME_BUTTON_STONE_IMG_PATH = 'img/game_button/stone/'

GAME_BUTTON_TEXT_COLOR_ACTIVE = (250, 221, 0) #(20, 20, 20)
GAME_BUTTON_TEXT_COLOR_PASSIVE = (220, 220, 220) #(20, 20, 20)
GAME_BUTTON_TEXT_COLOR_SHADOW = (20, 20, 20) #(250, 221, 0)

GAME_BUTTON_FONT_SIZE = FS_BUTTON                  # was int(0.03 * _FS)
GAME_BUTTON_TEXT_SHIFT_X = -int(0.02 * SCREEN_WIDTH)
GAME_BUTTON_TEXT_SHIFT_Y = int(0.06 * SCREEN_HEIGHT)

GAME_BUTTON_STONE_WIDTH = int(0.1 * SCREEN_WIDTH)
GAME_BUTTON_SYMBOL_WIDTH = int(0.07 * SCREEN_WIDTH)
GAME_BUTTON_GLOW_WIDTH = int(0.06 * SCREEN_WIDTH)

GAME_BUTTON_GLOW_SHIFT = int(0.00 * SCREEN_WIDTH)

GAME_BUTTON_STONE_BIG_WIDTH = int(0.15 * SCREEN_WIDTH)
GAME_BUTTON_SYMBOL_BIG_WIDTH = int(0.12 * SCREEN_WIDTH)
GAME_BUTTON_GLOW_BIG_WIDTH = int(0.08 * SCREEN_WIDTH)

HAND_BUTTON_STONE_WIDTH = int(0.06 * SCREEN_WIDTH)
HAND_BUTTON_SYMBOL_WIDTH = int(0.03 * SCREEN_WIDTH)
HAND_BUTTON_GLOW_WIDTH = int(0.04 * SCREEN_WIDTH)

HAND_BUTTON_STONE_BIG_WIDTH = int(0.06 * SCREEN_WIDTH)
HAND_BUTTON_SYMBOL_BIG_WIDTH = int(0.035 * SCREEN_WIDTH)
HAND_BUTTON_GLOW_BIG_WIDTH = int(0.05 * SCREEN_WIDTH)

HAND_BUTTON_GLOW_SHIFT = int(0.002 * SCREEN_WIDTH)

# ButtonShifter
RIGHT_ARROW_IMG_PATH = 'img/utils/right_arrow.png'
LEFT_ARROW_IMG_PATH = 'img/utils/left_arrow.png'
ARROW_WIDTH = int(0.022 * SCREEN_WIDTH * _UI_SCALE)
ARROW_HEIGHT = int(0.027 * SCREEN_WIDTH * _UI_SCALE)
ARROW_BIG_WIDTH = int(0.025 * SCREEN_WIDTH * _UI_SCALE)
ARROW_BIG_HEIGHT = int(0.031 * SCREEN_WIDTH * _UI_SCALE)
ARROW_GLOW_WIDTH = int(0.032 * SCREEN_WIDTH * _UI_SCALE)
ARROW_GLOW_BIG_WIDTH = int(0.036 * SCREEN_WIDTH * _UI_SCALE)


# BUTTONS
HAND_BUTTON_WIDTH = int(0.05 * SCREEN_WIDTH)
BUILD_BUTTON_WIDTH = int(0.1 * SCREEN_WIDTH)
ACTION_BUTTON_WIDTH = int(0.1 * SCREEN_WIDTH)
FIELD_BUTTON_WIDTH = int(0.06 * SCREEN_WIDTH)
FIELD_BUTTON_WIDTH_BIG = int(0.07 * SCREEN_WIDTH)
FIELD_BUTTON_GLOW_WIDTH = int(0.08 * SCREEN_WIDTH)
FIELD_BUTTON_GLOW_WIDTH_BIG = int(0.09 * SCREEN_WIDTH)
LETTER_BUTTON_WIDTH = int(0.055 * SCREEN_WIDTH)
LETTER_BUTTON_WIDTH_BIG = int(0.065 * SCREEN_WIDTH)
TUTORIAL_BUTTON_WIDTH = int(0.06 * SCREEN_WIDTH)
TUTORIAL_BUTTON_WIDTH_BIG = int(0.07 * SCREEN_WIDTH)
BATTLE_BUTTON_WIDTH = int(0.06 * SCREEN_WIDTH)
BATTLE_BUTTON_WIDTH_BIG = int(0.07 * SCREEN_WIDTH)
BATTLE_SHOP_BUTTON_WIDTH = int(0.06 * SCREEN_WIDTH)
BATTLE_SHOP_BUTTON_WIDTH_BIG = int(0.07 * SCREEN_WIDTH)
_HOME_SCALE = min(_UI_SCALE, 1.45)  # cap mobile home button growth (sidebar is shifted down to make room)
HOME_BUTTON_WIDTH = int(0.04 * SCREEN_WIDTH * _HOME_SCALE)
HOME_BUTTON_WIDTH_BIG = int(0.045 * SCREEN_WIDTH * _HOME_SCALE)
HOME_BUTTON_GLOW_WIDTH = int(0.06 * SCREEN_WIDTH * _HOME_SCALE)
HOME_BUTTON_GLOW_WIDTH_BIG = int(0.07 * SCREEN_WIDTH * _HOME_SCALE)




# ConfirmButton  (uses the same button art as the login menu)
CONFIRM_BUTTON_IMG_PATH = 'img/menu_button/menu_button2.png'
CONFIRM_BUTTON_IMG_DISABLED_PATH = 'img/menu_button/menu_button_greyscale.png'
CONFIRM_BUTTON_GLOW_DIR = 'img/menu_button/glow/'
CONFIRM_BUTTON_GLOW_W_FACTOR = 1.2
CONFIRM_BUTTON_GLOW_H_FACTOR = 2.0
CONFIRM_BUTTON_WIDTH = int(0.09 * SCREEN_WIDTH)
CONFIRM_BUTTON_HEIGHT = int(0.04 * SCREEN_HEIGHT)

CONFIRM_BUTTON_TEXT_COLOR_HOVERED = (20, 20, 20)
CONFIRM_BUTTON_TEXT_COLOR_ACTIVE = (20, 20, 20)
CONFIRM_BUTTON_TEXT_COLOR_PASSIVE = (240, 240, 240)
CONFIRM_BUTTON_TEXT_COLOR_DISABLED = (160, 150, 140)

CONFIRM_BUTTON_FONT_SIZE = FS_BUTTON               # was int(0.03 * _FS)
CONFIRM_BUTTON_FONT_SIZE_SMALL = FS_SMALL          # was int(0.02 * _FS)

# ScrollTextListShifter
SCROLL_TEXT_COLOR = (240, 228, 205)             # warm cream on brown bg
SCROLL_TEXT_TITLE_COLOR = (250, 221, 0)          # gold title
SCROLL_TEXT_SECTION_COLOR = (220, 195, 155)      # muted warm for section headers
SCROLL_TEXT_DIVIDER_COLOR = (140, 105, 65)       # warm brown divider
SCROLL_TEXT_MAX_WIDTH = int(0.15 * SCREEN_WIDTH)  # wider to fill panel

# Scroll font sizes (larger for readability)
SCROLL_FONT_SIZE_TITLE = FS_HEADING                # was int(0.026 * _FS)
SCROLL_FONT_SIZE_BODY = FS_BODY                    # was int(0.022 * _FS)
SCROLL_FONT_SIZE_SMALL = int(FS_SMALL * 0.95)      # was int(0.019 * _FS)  →  0.02 * 0.95 = 0.019
SCROLL_ICON_SIZE = int(0.025 * _FS)                 # resource / check icons
SCROLL_SKILL_ICON_SIZE = int(0.032 * _FS)            # skill icons (slightly larger)

# Scroll chevron arrows (programmatic, replaces image-based arrows)
SCROLL_CHEVRON_SIZE = int(0.014 * SCREEN_HEIGHT * _UI_SCALE)   # half-size of the chevron
SCROLL_CHEVRON_COLOR = (180, 155, 110)             # warm muted gold
SCROLL_CHEVRON_HOVER_COLOR = (250, 221, 0)         # bright gold on hover
SCROLL_CHEVRON_LINE_W = max(2, int(0.003 * SCREEN_HEIGHT))

# Custom scroll panel (replaces scroll.png) — warm brown tone
SCROLL_PANEL_BG_CLR = (75, 55, 36, 230)           # warm brown (sits on parchment)
SCROLL_PANEL_BORDER_CLR = (120, 85, 42)           # warm brown border (echoes frame)
SCROLL_PANEL_BORDER_WIDTH = 2
SCROLL_PANEL_CORNER_R = int(0.008 * SCREEN_HEIGHT)
SCROLL_PANEL_INNER_CLR = (62, 46, 30, 170)        # subtle inner depth
SCROLL_PANEL_PAD = int(0.006 * SCREEN_HEIGHT)      # inner padding

# Color toggle pill buttons (replaces image-based buttons)
COLOR_TOGGLE_W = (int(0.18 * SCREEN_WIDTH) - int(0.008 * SCREEN_WIDTH)) // 2
COLOR_TOGGLE_H = int(0.035 * SCREEN_HEIGHT * _UI_SCALE)
COLOR_TOGGLE_CORNER_R = int(0.006 * SCREEN_HEIGHT)
COLOR_TOGGLE_GAP = int(0.008 * SCREEN_WIDTH)
COLOR_TOGGLE_FONT_SIZE = FS_SMALL if _IS_MOBILE else FS_BODY
COLOR_TOGGLE_BG_CLR = (50, 38, 28, 180)           # dark brown
COLOR_TOGGLE_BG_ACTIVE_CLR = (72, 52, 34, 220)    # lighter brown when active
COLOR_TOGGLE_BG_HOVER_CLR = (80, 58, 38, 220)     # hover
COLOR_TOGGLE_BORDER_CLR = (110, 85, 55)            # muted brown
COLOR_TOGGLE_BORDER_ACTIVE_CLR = (200, 170, 70)    # gold when active (fallback)
COLOR_TOGGLE_TEXT_CLR = (220, 210, 190)            # warm cream (readable on dark bg)
COLOR_TOGGLE_TEXT_ACTIVE_CLR = (250, 221, 0)       # gold when active (fallback)

# Per-colour accents for Djungle / Himalaya
COLOR_TOGGLE_DJUNGLE_ACCENT = (80, 180, 80)        # green
COLOR_TOGGLE_DJUNGLE_BG_ACTIVE = (35, 65, 35, 220) # dark green tint
COLOR_TOGGLE_HIMALAYA_ACCENT = (80, 130, 210)      # blue
COLOR_TOGGLE_HIMALAYA_BG_ACTIVE = (30, 45, 75, 220) # dark blue tint
