from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

# BUTTOM
BUTTON_IMG_PATH = 'img/button/'

# MENU BUTTON
MENU_BUTTON_IMG_PATH = 'img/menu_button/menu_button.png'
MENU_BUTTON_GLOW_DIR = 'img/menu_button/glow/'
MENU_BUTTON_WIDTH = int(0.12 * SCREEN_WIDTH)
MENU_BUTTON_HEIGHT = int(0.06 * SCREEN_HEIGHT)

MENU_BUTTON_TEXT_COLOR_HOVERED = (20, 20, 20)
MENU_BUTTON_TEXT_COLOR_ACTIVE = (20, 20, 20)
MENU_BUTTON_TEXT_COLOR_PASSIVE = (240, 240, 240)

# HAND BUTTON
MAIN_HAND_X = int(0.05 * SCREEN_WIDTH)
MAIN_HAND_Y = int(0.8 * SCREEN_HEIGHT)

SIDE_HAND_X = int(0.5 * SCREEN_WIDTH)
SIDE_HAND_Y = int(0.8 * SCREEN_HEIGHT)

BUILD_BUTTON_X = int(0.84 * SCREEN_WIDTH)
BUILD_BUTTON_Y = int(0.86 * SCREEN_HEIGHT)

ACTION_BUTTON_X = int(0.94 * SCREEN_WIDTH)
ACTION_BUTTON_Y = int(0.86 * SCREEN_HEIGHT)


# GAME BUTTON
GAME_BUTTON_SYMBOL_IMG_PATH = 'img/game_button/symbol/'
GAME_BUTTON_GLOW_IMG_PATH = 'img/game_button/glow/'
GAME_BUTTON_STONE_IMG_PATH = 'img/game_button/stone/'

GAME_BUTTON_TEXT_COLOR_ACTIVE = (250, 221, 0) #(20, 20, 20)
GAME_BUTTON_TEXT_COLOR_PASSIVE = (220, 220, 220) #(20, 20, 20)
GAME_BUTTON_TEXT_COLOR_SHADOW = (20, 20, 20) #(250, 221, 0)

GAME_BUTTON_FONT_SIZE = int(0.03 * SCREEN_HEIGHT)
GAME_BUTTON_TEXT_SHIFT_X = -int(0.02 * SCREEN_WIDTH)
GAME_BUTTON_TEXT_SHIFT_Y = int(0.06 * SCREEN_HEIGHT)

GAME_BUTTON_STONE_WIDTH = int(0.1 * SCREEN_WIDTH)
GAME_BUTTON_SYMBOL_WIDTH = int(0.07 * SCREEN_WIDTH)
GAME_BUTTON_GLOW_WIDTH = int(0.06 * SCREEN_WIDTH)

GAME_BUTTON_GLOW_SHIFT = int(0.00 * SCREEN_WIDTH)

GAME_BUTTON_STONE_BIG_WIDTH = int(0.15 * SCREEN_WIDTH)
GAME_BUTTON_SYMBOL_BIG_WIDTH = int(0.12 * SCREEN_WIDTH)
GAME_BUTTON_GLOW_BIG_WIDTH = int(0.08 * SCREEN_WIDTH)

HAND_BUTTON_STONE_WIDTH = int(0.06 * SCREEN_WIDTH)
HAND_BUTTON_SYMBOL_WIDTH = int(0.03 * SCREEN_WIDTH)
HAND_BUTTON_GLOW_WIDTH = int(0.04 * SCREEN_WIDTH)

HAND_BUTTON_STONE_BIG_WIDTH = int(0.06 * SCREEN_WIDTH)
HAND_BUTTON_SYMBOL_BIG_WIDTH = int(0.035 * SCREEN_WIDTH)
HAND_BUTTON_GLOW_BIG_WIDTH = int(0.05 * SCREEN_WIDTH)

HAND_BUTTON_GLOW_SHIFT = int(0.002 * SCREEN_WIDTH)

# BUILD
BUILD_FIGURE_BACKGROUND_IMG_PATH = 'img/background/option_box.png'
BUILD_FIGURE_BACKGROUND_IMG_WIDTH = int(0.45 * SCREEN_WIDTH)
BUILD_FIGURE_BACKGROUND_IMG_HEIGHT = int(0.55 * SCREEN_HEIGHT)

# ButtonShifter
RIGHT_ARROW_IMG_PATH = 'img/utils/right_arrow.png'
LEFT_ARROW_IMG_PATH = 'img/utils/left_arrow.png'
ARROW_WIDTH = int(0.03 * SCREEN_WIDTH)
ARROW_HEIGHT = int(0.03 * SCREEN_WIDTH)
ARROW_BIG_WIDTH = int(0.035 * SCREEN_WIDTH)
ARROW_BIG_HEIGHT = int(0.035 * SCREEN_WIDTH)
ARROW_GLOW_WIDTH = int(0.06 * SCREEN_WIDTH)
ARROW_GLOW_BIG_WIDTH = int(0.08 * SCREEN_WIDTH)


# BUTTONS
HAND_BUTTON_WIDTH = int(0.05 * SCREEN_WIDTH)
BUILD_BUTTON_WIDTH = int(0.1 * SCREEN_WIDTH)
ACTION_BUTTON_WIDTH = int(0.1 * SCREEN_WIDTH)

