from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

FIELD_ICON_START_X = int(0.23 * SCREEN_WIDTH)
FIELD_ICON_START_Y = int(0.35 * SCREEN_HEIGHT)
FIELD_ICON_WIDTH = int(0.115 * SCREEN_WIDTH)
FIELD_ICON_PADDING_X = int(0.0 * SCREEN_WIDTH)
FIELD_ICON_PADDING_Y = int(0.02 * SCREEN_HEIGHT)

FIELD_SELF_X = int(0.17 * SCREEN_WIDTH)
FIELD_OPPONENT_X = int(0.54 * SCREEN_WIDTH)
FIELD_HEIGHT = int(0.6 * SCREEN_HEIGHT)
FIELD_Y = int(0.08 * SCREEN_HEIGHT)

FIELD_FILL_COLOR = (106, 58, 24) #(40, 40, 40)
FIELD_BORDER_COLOR = (25, 10, 4) #(100, 100, 100)
FIELD_BORDER_WIDTH = 3
FIELD_TRANSPARENCY = 200

