from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

FIELD_ICON_START_X = int(0.25 * SCREEN_WIDTH)
FIELD_ICON_START_Y = int(0.35 * SCREEN_HEIGHT)
FIELD_ICON_WIDTH = int(0.1 * SCREEN_WIDTH)
FIELD_ICON_PADDING_X = int(0.02 * SCREEN_WIDTH)