# Copyright (c) 2026 Marc Stieffenhofer. All rights reserved.
# See LICENSE file in the project root for full license information.
from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT, _FS, _UI_SCALE

# PATHS
FIGURE_ICON_IMG_DIR = 'img/figures/icons/'
FIGURE_ICON_GREYSCALE_IMG_DIR = 'img/figures/icons_greyscale/'
FIGURE_ICON_SMALL_IMG_DIR = 'img/figures/icons_small/'
FIGURE_ICON_SMALL_GREYSCALE_IMG_DIR = 'img/figures/icons_small_greyscale/'
FIGURE_FRAME_IMG_DIR = 'img/figures/frames/'
FIGURE_FRAME_GREYSCALE_IMG_DIR = 'img/figures/frames_greyscale/'
FIGURE_FRAME_HIDDEN_IMG_DIR = 'img/figures/frames_hidden/'
FIGURE_FRAME_HIDDEN_GREYSCALE_IMG_DIR = 'img/figures/frames_hidden_greyscale/'
FIGURE_GLOW_IMG_DIR = 'img/game_button/glow_rect/'
    

FIGURE_WIDTH = int(0.1 * SCREEN_WIDTH)
FIGURE_HEIGHT = int(0.1 * SCREEN_WIDTH)


# FIGURE ICON
FIGURE_ICON_BIG_SCALE = 1.2
FRAME_FIGURE_SCALE = 1.4

FIGURE_NAME_BG_COLOR = (235, 210, 170)          # warm parchment
FIGURE_NAME_INFO_BG_COLOR = (200, 172, 132)       # slightly darker parchment for info section
FIGURE_NAME_FRAME_COLOR = (120, 72, 36)           # rich warm brown border
FIGURE_NAME_SEP_COLOR = (170, 140, 100)           # soft separator
FIGURE_NAME_SHADOW_COLOR = (40, 30, 18, 90)       # subtle drop shadow
FIGURE_NAME_PADDING = int(0.005 * SCREEN_WIDTH)
# On mobile, compress info-row vertical padding to save space
FIGURE_NAME_INFO_PADDING_SCALE = 0.5 if _UI_SCALE > 1.0 else 1.0
FIGURE_NAME_CORNER_R = int(0.005 * SCREEN_HEIGHT)
FIGURE_NAME_SHADOW_OFFSET = max(2, int(0.003 * SCREEN_HEIGHT))

FIGURE_ICON_MASK_WIDTH = int(0.08 * SCREEN_WIDTH)
FIGURE_ICON_MASK_HEIGHT = int(0.08 * SCREEN_WIDTH)
FIGURE_ICON_MASK_BIG_WIDTH = int(0.066 * SCREEN_WIDTH)
FIGURE_ICON_MASK_BIG_HEIGHT = int(0.066 * SCREEN_WIDTH)
FIGURE_ICON_WIDTH = FIGURE_ICON_MASK_WIDTH*0.9
FIGURE_ICON_HEIGHT = FIGURE_ICON_MASK_HEIGHT*0.9
FIGURE_ICON_BIG_WIDTH = FIGURE_ICON_MASK_BIG_WIDTH*0.9
FIGURE_ICON_BIG_HEIGHT = FIGURE_ICON_MASK_BIG_HEIGHT*0.9
FIGURE_ICON_GLOW_WIDTH = int(0.09 * SCREEN_WIDTH)
FIGURE_ICON_GLOW_BIG_WIDTH = int(0.12 * SCREEN_WIDTH)
FIGURE_ICON_DELTA_X = int(0.08 * SCREEN_WIDTH)

FIGURE_ICON_SIN_AMPL = int(0.005 * SCREEN_HEIGHT)

FIGURE_ICON_CAPTION_COLOR = (95, 42, 22)

FIGURE_ICON_FONT_CAPTION_FONT_SIZE = int(0.02 * _FS)
FIGURE_ICON_FONT_CAPTION_BIG_FONT_SIZE = int(0.025 * _FS)


# SUIT ICON
SUIT_ICON_IMG_PATH = 'img/suits/'
SUIT_ICON_DARKWHITE_IMG_PATH = 'img/suits/darkwhite/'

SUIT_ICON_WIDTH = int(0.03 * SCREEN_WIDTH)
SUIT_ICON_HEIGHT = int(0.03 * SCREEN_WIDTH)

SUIT_ICON_BIG_WIDTH = int(0.037 * SCREEN_WIDTH)
SUIT_ICON_BIG_HEIGHT = int(0.037 * SCREEN_WIDTH)
SUIT_ICON_GLOW_WIDTH = int(0.06 * SCREEN_WIDTH)
SUIT_ICON_GLOW_BIG_WIDTH = int(0.06 * SCREEN_WIDTH)