from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

# PATHS
FIGURE_ICON_IMG_DIR = 'img/figures/icons/'
FIGURE_ICON_GREYSCALE_IMG_DIR = 'img/figures/icons_greyscale/'
FIGURE_FRAME_IMG_DIR = 'img/figures/frames/'
FIGURE_FRAME_HIDDEN_IMG_DIR = 'img/figures/frames_hidden/'
    

FIGURE_WIDTH = int(0.1 * SCREEN_WIDTH)
FIGURE_HEIGHT = int(0.1 * SCREEN_WIDTH)


# FIGURE ICON
FIGURE_ICON_BIG_SCALE = 1.2
FRAME_FIGURE_SCALE = 1.8

FIGURE_NAME_BG_COLOR = (240, 218, 186)
FIGURE_NAME_FRAME_COLOR = (95, 42, 22)
FIGURE_NAME_PADDING = int(0.002 * SCREEN_WIDTH)

FIGURE_ICON_MASK_WIDTH = int(0.08 * SCREEN_WIDTH)
FIGURE_ICON_MASK_HEIGHT = int(0.08 * SCREEN_WIDTH)
FIGURE_ICON_MASK_BIG_WIDTH = int(0.066 * SCREEN_WIDTH)
FIGURE_ICON_MASK_BIG_HEIGHT = int(0.066 * SCREEN_WIDTH)
FIGURE_ICON_WIDTH = FIGURE_ICON_MASK_WIDTH*0.9
FIGURE_ICON_HEIGHT = FIGURE_ICON_MASK_HEIGHT*0.9
FIGURE_ICON_BIG_WIDTH = FIGURE_ICON_MASK_BIG_WIDTH*0.9
FIGURE_ICON_BIG_HEIGHT = FIGURE_ICON_MASK_BIG_HEIGHT*0.9
FIGURE_ICON_GLOW_WIDTH = int(0.12 * SCREEN_WIDTH)
FIGURE_ICON_GLOW_BIG_WIDTH = int(0.13 * SCREEN_WIDTH)
FIGURE_ICON_DELTA_X = int(0.08 * SCREEN_WIDTH)

FIGURE_ICON_SIN_AMPL = int(0.005 * SCREEN_HEIGHT)

FIGURE_ICON_CAPTION_COLOR = (95, 42, 22)

FIGURE_ICON_FONT_CAPTION_FONT_SIZE = int(0.02 * SCREEN_HEIGHT)
FIGURE_ICON_FONT_CAPTION_BIG_FONT_SIZE = int(0.025 * SCREEN_HEIGHT)


# SUIT ICON
SUIT_ICON_IMG_PATH = 'img/suits/'
SUIT_ICON_DARKWHITE_IMG_PATH = 'img/suits/darkwhite/'

SUIT_ICON_WIDTH = int(0.03 * SCREEN_WIDTH)
SUIT_ICON_HEIGHT = int(0.03 * SCREEN_WIDTH)

SUIT_ICON_BIG_WIDTH = int(0.037 * SCREEN_WIDTH)
SUIT_ICON_BIG_HEIGHT = int(0.037 * SCREEN_WIDTH)
SUIT_ICON_GLOW_WIDTH = int(0.06 * SCREEN_WIDTH)
SUIT_ICON_GLOW_BIG_WIDTH = int(0.06 * SCREEN_WIDTH)