from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

# PATHS
FIGURE_VISIBLE_IMG_PATH = 'img/figures/visible/'
FIGURE_HIDDEN_IMG_PATH = 'img/figures/hidden_with_label/'
FIGURE_ICON_IMG_PATH = 'img/figures/icon/'
FIGURE_ICON_DARKWHITE_IMG_PATH = 'img/figures/icon_darkwhite/'
FIGURE_EMPTY_IMG_PATH = 'img/figures/empty/'

# Main Screen
MAIN_SCREEN_X = int(0.1 * SCREEN_WIDTH)
MAIN_SCREEN_Y = int(0.1 * SCREEN_HEIGHT)

FIGURE_WIDTH = int(0.1 * SCREEN_WIDTH)
FIGURE_HEIGHT = int(0.1 * SCREEN_WIDTH)

# FIGURE ICON
FIGURE_ICON_MASK_WIDTH = int(0.06 * SCREEN_WIDTH)
FIGURE_ICON_MASK_HEIGHT = int(0.06 * SCREEN_WIDTH)
FIGURE_ICON_MASK_BIG_WIDTH = int(0.066 * SCREEN_WIDTH)
FIGURE_ICON_MASK_BIG_HEIGHT = int(0.066 * SCREEN_WIDTH)
FIGURE_ICON_WIDTH = FIGURE_ICON_MASK_WIDTH*0.9
FIGURE_ICON_HEIGHT = FIGURE_ICON_MASK_HEIGHT*0.9
FIGURE_ICON_BIG_WIDTH = FIGURE_ICON_MASK_BIG_WIDTH*0.9
FIGURE_ICON_BIG_HEIGHT = FIGURE_ICON_MASK_BIG_HEIGHT*0.9
FIGURE_ICON_GLOW_WIDTH = int(0.12 * SCREEN_WIDTH)
FIGURE_ICON_GLOW_BIG_WIDTH = int(0.13 * SCREEN_WIDTH)
FIGURE_ICON_DELTA_X = int(0.08 * SCREEN_WIDTH)

FIGURE_ICON_SIN_AMPL = int(0.01 * SCREEN_HEIGHT)

FIGURE_ICON_CAPTION_COLOR = (20, 20, 20)

FIGURE_ICON_FONT_CAPTION_FONT_SIZE = int(0.02 * SCREEN_HEIGHT)
FIGURE_ICON_FONT_CAPTION_BIG_FONT_SIZE = int(0.022 * SCREEN_HEIGHT)


# SUIT ICON
SUIT_ICON_IMG_PATH = 'img/suits/'
SUIT_ICON_DARKWHITE_IMG_PATH = 'img/suits/darkwhite/'

SUIT_ICON_WIDTH = int(0.04 * SCREEN_WIDTH)
SUIT_ICON_HEIGHT = int(0.04 * SCREEN_WIDTH)

SUIT_ICON_BIG_WIDTH = int(0.05 * SCREEN_WIDTH)
SUIT_ICON_BIG_HEIGHT = int(0.05 * SCREEN_WIDTH)
SUIT_ICON_GLOW_WIDTH = int(0.08 * SCREEN_WIDTH)
SUIT_ICON_GLOW_BIG_WIDTH = int(0.10 * SCREEN_WIDTH)