from config.screen_settings import SCREEN_HEIGHT

# Font settings
FONT_PATH = None
FONT_SIZE = int(0.05 * SCREEN_HEIGHT)
FONT_SIZE_DETAIL = int(0.02 * SCREEN_HEIGHT)
FONT_SIZE_BUTTON = int(0.03 * SCREEN_HEIGHT)
LOGOUT_FONT_SIZE = int(0.03 * SCREEN_HEIGHT)

# Timings
MESSAGE_DURATION = 5000
