from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

INFO_SCROLL_RESOURCES_X = int(0.008 * SCREEN_WIDTH)
INFO_SCROLL_RESOURCES_Y = int(0.25 * SCREEN_HEIGHT)

INFO_SCROLL_SLOTS_X = int(0.008 * SCREEN_WIDTH)
INFO_SCROLL_SLOTS_Y = int(0.46 * SCREEN_HEIGHT)


INFO_SCROLL_WIDTH = int(0.107 * SCREEN_WIDTH)
INFO_SCROLL_HEIGHT = int(0.2 * SCREEN_HEIGHT)
INFO_SCROLL_BG_IMG_PATH = 'img/background/paper4.png'
GLOW_RECT_IMG_PATH = 'img/glow/rect/'

INFO_SCROLL_FONT_SIZE = int(0.02 * SCREEN_HEIGHT)
INFO_SCROLL_Y_TITLE_MARGIN = int(0.04 * SCREEN_HEIGHT)
INFO_SCROLL_TITLE_SPACING = int(0.02 * SCREEN_HEIGHT)
INFO_SCROLL_LINE_SPACING = int(0.04 * SCREEN_HEIGHT)
INFO_SCROLL_TEXT_COLOR = (20, 20, 20)
INFO_SCROLL_SCORE_COLOR = (200, 200, 200)
INFO_SCROLL_TEXT_MARGIN = int(0.003 * SCREEN_WIDTH)
INFO_SCROLL_TEXT_PADDING = int(0.002 * SCREEN_WIDTH)

INFO_SCROLL_ICON_SIZE = int(0.019 * SCREEN_WIDTH)
INFO_SCROLL_ICON_MARGIN = int(0.024 * SCREEN_WIDTH)
INFO_SCROLL_ICON_SPACING = int(0.01 * SCREEN_WIDTH)



RESOURCE_ICON_IMG_PATH_DICT = {
    'rice': 'img/resource_icons/rice.png',
    'wood': 'img/resource_icons/wood.png',
    'stone': 'img/resource_icons/stone.png',
    'sword': 'img/resource_icons/sword.png',
    'shield': 'img/resource_icons/shield.png',
    'meat': 'img/resource_icons/meat.png',
}

SLOT_ICON_IMG_PATH_DICT = {
    'castle': 'img/slot_icons/castle.png',
    'village': 'img/slot_icons/village.png',
    'military': 'img/slot_icons/military.png',
}

# SCOREBORD SCROLL
SCOREBOARD_SCROLL_X = int(0.0 * SCREEN_WIDTH)
SCOREBOARD_SCROLL_Y = int(0.01 * SCREEN_HEIGHT)
SCOREBOARD_SCROLL_WIDTH = int(0.12 * SCREEN_WIDTH)
SCOREBOARD_SCROLL_HEIGHT = int(0.14 * SCREEN_HEIGHT)
SCOREBOARD_SCROLL_Y_TEXT_MARGIN = int(0.07 * SCREEN_HEIGHT)
SCOREBOARD_SCROLL_X_TEXT_MARGIN = int(0.02 * SCREEN_WIDTH)
SCOREBOARD_SCROLL_SPACER = int(0.01 * SCREEN_WIDTH)
SCOREBOARD_SCROLL_BG_IMG_PATH = 'img/background/paper3.png'

SCOREBOARD_SCROLL_FONT_SIZE = int(0.02 * SCREEN_HEIGHT)
SCOREBOARD_SCROLL_FONT_TITLE_SIZE = int(0.025 * SCREEN_HEIGHT)
SCOREBOARD_SCROLL_NUMBER_FONT_SIZE = int(0.04 * SCREEN_HEIGHT)
SCOREBOARD_SCROLL_LINE_SPACING = int(0.02 * SCREEN_HEIGHT)
SCOREBOARD_SCROLL_TEXT_COLOR = (20, 20, 20)

SCOREBOARD_CROSS_COLOR = (20, 20, 20)
SCOREBOARD_CROSS_ALPHA = 80
SCOREBOARD_CROSS_WIDTH = int(0.0015 * SCREEN_WIDTH)
SCOREBOARD_CROSS_SPACING = int(0.03 * SCREEN_WIDTH)
SCOREBOARD_CELL_TEXT_SPACING = int(0.002 * SCREEN_WIDTH)
SCOREBOARD_LIMIT_SECTION_HEIGHT = int(0.03 * SCREEN_HEIGHT)






