from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

MSG_BACKGROUND_COLOR = (0, 0, 0)

MSG_MAX_WIDTH = int(0.6 * SCREEN_WIDTH)
MSG_MAX_HEIGHT = int(0.3 * SCREEN_HEIGHT)

MSG_TEXT_BOX_X = int(0.2 * SCREEN_WIDTH)
MSG_TEXT_BOX_Y = int(0.2 * SCREEN_HEIGHT)
MSG_TEXT_BOX_WIDTH = int(0.6 * SCREEN_WIDTH)
MSG_TEXT_BOX_HEIGHT = int(0.5 * SCREEN_HEIGHT)

MSG_LOG_BUTTON_X = int(0.2 * SCREEN_WIDTH)
MSG_LOG_BUTTON_Y = int(0.2 * SCREEN_HEIGHT)
MSG_CHAT_BUTTON_X = int(0.2 * SCREEN_WIDTH)
MSG_CHAT_BUTTON_Y = int(0.25 * SCREEN_HEIGHT)
MSG_SEND_BUTTON_X = int(0.7 * SCREEN_WIDTH)
MSG_SEND_BUTTON_Y = int(0.7 * SCREEN_HEIGHT)

MSG_INPUT_X = int(0.3 * SCREEN_WIDTH)
MSG_INPUT_Y = int(0.6 * SCREEN_HEIGHT)

MSG_TEXT_X = int(0.3 * SCREEN_WIDTH)
MSG_TEXT_Y = int(0.2 * SCREEN_HEIGHT)

MSG_BACKGROUND_COLOR = (30, 30, 30)  # General background color
MSG_TEXT_COLOR = (255, 255, 255)  # Text color
LOG_MSG_BG_COLOR = (50, 50, 150)  # Background for log messages
CHAT_MSG_BG_COLOR = (50, 150, 50)  # Background for chat messages

SCROLLBAR_COLOR = (100, 100, 100)
SCROLLBAR_HANDLE_COLOR = (150, 150, 150)

