from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

INPUTFIELD_BORDER_COLOR_ACTIVE = (250, 170, 0)
INPUTFIELD_BORDER_COLOR_PASSIVE = (60, 60, 60)
INPUTFIELD_TEXT_COLOR_HEADER= (220, 220, 220)
INPUTFIELD_FONT_SIZE = int(0.04 * SCREEN_HEIGHT)
INPUTFIELD_FONT_SIZE_TITLE = int(0.03 * SCREEN_HEIGHT)
INPUTFIELD_COLOR_PASSIVE = (100, 100, 100)
INPUTFIELD_COLOR_ACTIVE = (120, 120, 120) #(250, 170, 0)

INPUTFIELD_WIDTH = int(0.55 * SCREEN_WIDTH)
INPUTFIELD_WIDTH_SMALL = int(0.3 * SCREEN_WIDTH)
INPUTFIELD_HEIGHT = int(0.04 * SCREEN_HEIGHT)

MSG_BACKGROUND_COLOR = (0, 0, 0)

MSG_FONT_SIZE = int(0.025 * SCREEN_HEIGHT)

MSG_MAX_WIDTH = int(0.8 * SCREEN_WIDTH)
MSG_MAX_HEIGHT = int(0.45 * SCREEN_HEIGHT)

MSG_TEXT_BOX_X = int(0.24 * SCREEN_WIDTH)
MSG_TEXT_BOX_Y = int(0.07 * SCREEN_HEIGHT)
MSG_TEXT_BOX_WIDTH = int(0.64 * SCREEN_WIDTH)
MSG_TEXT_BOX_HEIGHT = int(0.52 * SCREEN_HEIGHT)

MSG_LOG_BUTTON_X = int(0.15 * SCREEN_WIDTH)
MSG_LOG_BUTTON_Y = int(0.07 * SCREEN_HEIGHT)
MSG_CHAT_BUTTON_X = int(0.15 * SCREEN_WIDTH)
MSG_CHAT_BUTTON_Y = int(0.12 * SCREEN_HEIGHT)
MSG_SEND_BUTTON_X = int(0.8 * SCREEN_WIDTH)
MSG_SEND_BUTTON_Y = int(0.635 * SCREEN_HEIGHT)

MSG_INPUT_X = int(0.24 * SCREEN_WIDTH)
MSG_INPUT_Y = int(0.64 * SCREEN_HEIGHT)

MSG_TEXT_X = int(0.27 * SCREEN_WIDTH)
MSG_TEXT_Y = int(0.10 * SCREEN_HEIGHT)

MSG_BACKGROUND_COLOR = (30, 30, 30)  # General background color
MSG_TEXT_COLOR = (255, 255, 255)  # Text color
LOG_MSG_BG_COLOR = (50, 50, 150)  # Background for log messages
CHAT_MSG_BG_COLOR = (50, 150, 50)  # Background for chat messages

SCROLLBAR_COLOR = (196, 130, 77)
#SCROLLBAR_HANDLE_COLOR = (83, 12, 2)
SCROLLBAR_HANDLE_COLOR_ACTIVE = (250, 170, 0)
SCROLLBAR_HANDLE_COLOR_PASSIVE = (83, 12, 2)
SCROLLBAR_HEIGHT = int(0.484 * SCREEN_HEIGHT)
SCROLLBAR_WIDTH = int(0.005 * SCREEN_WIDTH)
SCROLLBAR_X = int(0.858 * SCREEN_WIDTH)
SCROLLBAR_Y = int(0.08795 * SCREEN_HEIGHT)

LOG_MSG_OPP_BG_COLOR = (13, 56, 139)  # Background for log messages
LOG_MSG_SELF_BG_COLOR = (13, 106, 51)  # Background for log messages
CHAT_MSG_SELF_BG_COLOR = (120, 60, 26)  # Background for chat messages
CHAT_MSG_OPP_BG_COLOR = (83, 12, 2)  # Background for chat messages
MSG_BG_TRANSPARENCY = 200


