# Screen settings
SCREEN_WIDTH = 1920 #1600 #1920
SCREEN_HEIGHT = 1080 #900 #1080
SCREEN_CAPTION = 'Nepal Kings'

# Sizes
CENTER_X = int(0.5 * SCREEN_WIDTH)
CENTER_Y = int(0.5 * SCREEN_HEIGHT)

CONTROL_BUTTON_WIDTH = int(0.15 * SCREEN_WIDTH)
CONTROL_BUTTON_HEIGHT = int(0.04 * SCREEN_HEIGHT)

MESSAGE_SPACING = int(0.04 * SCREEN_HEIGHT)

TINY_SPACER_X = int(0.01 * SCREEN_WIDTH)
TINY_SPACER_Y = int(0.01 * SCREEN_HEIGHT)

SMALL_SPACER_X = int(0.02 * SCREEN_WIDTH)
SMALL_SPACER_Y = int(0.02 * SCREEN_HEIGHT)

BIG_SPACER_X = int(0.1 * SCREEN_WIDTH)
BIG_SPACER_Y = int(0.1 * SCREEN_HEIGHT)

# Sub Screen settings
SUB_SCREEN_X = int(0.124 * SCREEN_WIDTH)
SUB_SCREEN_Y = int(0.01 * SCREEN_HEIGHT)


SUB_SCREEN_BACKGROUND_IMG_PATH = 'img/sub_screen/background_field.png'
SUB_BOX_BACKGROUND_IMG_PATH = 'img/sub_screen/background_dark.png'
SUB_SCREEN_BUTTON_IMG_PATH = 'img/sub_screen/button1.png'
SUB_BOX_SCROLL_BACKGROUND_IMG_PATH = 'img/sub_screen/scroll.png'
SUB_SCREEN_BACKGROUND_COLOR = (40, 40, 40)
SUB_SCREEN_BUTTON_TEXT_COLOR_ACTIVE = (248, 222, 0)  # Bright yellow for active state
SUB_SCREEN_BUTTON_TEXT_COLOR_PASSIVE = (60, 60, 60)  # Light cyan for dark turkis background
SUB_SCREEN_BUTTON_TEXT_COLOR_HOVERED = (255, 255, 255)  # White for hover state
SUB_SCREEN_BACKGROUND_TRANSPARENCY = 200
SUB_SCREEN_BACKGROUND_IMG_WIDTH = int(0.8 * SCREEN_WIDTH)
SUB_SCREEN_BACKGROUND_IMG_HEIGHT = int(0.73 * SCREEN_HEIGHT)
SUB_SCREEN_BUTTON_WIDTH = int(0.08 * SCREEN_WIDTH)
SUB_SCREEN_BUTTON_HEIGHT = int(0.035 * SCREEN_HEIGHT)
SUB_SCREEN_BUTTON_DELTA_X = int(0.09 * SCREEN_WIDTH)

SUB_SCREEN_TITLE_COLOR = (250, 221, 0)
SUB_SCREEN_TITLE_BG_COLOR = (62, 40, 22)
SUB_SCREEN_TITLE_BORDER_COLOR = (140, 105, 55)
SUB_SCREEN_TITLE_BORDER_WIDTH = 2
SUB_SCREEN_TITLE_PADDING = max(6, int(0.010 * SCREEN_HEIGHT))
SUB_SCREEN_TITLE_SHADOW_COLOR = (30, 20, 10)
SUB_SCREEN_TITLE_SHADOW_OFFSET = max(2, int(0.003 * SCREEN_HEIGHT))
SUB_SCREEN_TITLE_X = int(0.53 * SCREEN_WIDTH)
SUB_SCREEN_TITLE_Y = int(0.038 * SCREEN_HEIGHT)
SUB_SCREEN_TITLE_FONT_SIZE = int(0.034 * SCREEN_HEIGHT)
SUB_SCREEN_TITLE_CORNER_R = int(0.006 * SCREEN_HEIGHT)


MINI_CARD_WIDTH = int(0.02 * SCREEN_WIDTH)
MINI_CARD_HEIGHT = int(0.04 * SCREEN_HEIGHT)

