# Screen settings
SCREEN_WIDTH = 1920 #1600
SCREEN_HEIGHT = 1080 #900 
SCREEN_CAPTION = 'Nepal Kings'

# Sizes
CENTER_X = int(0.5 * SCREEN_WIDTH)
CENTER_Y = int(0.5 * SCREEN_HEIGHT)

CONTROL_BUTTON_WIDTH = int(0.15 * SCREEN_WIDTH)
CONTROL_BUTTON_HEIGHT = int(0.04 * SCREEN_HEIGHT)

SMALL_FIELD_WIDTH = int(0.375 * SCREEN_WIDTH)
SMALL_FIELD_HEIGHT = int(0.05 * SCREEN_HEIGHT)

MESSAGE_SPACING = int(0.04 * SCREEN_HEIGHT)

TINY_SPACER_X = int(0.01 * SCREEN_WIDTH)
TINY_SPACER_Y = int(0.01 * SCREEN_HEIGHT)

SMALL_SPACER_X = int(0.02 * SCREEN_WIDTH)
SMALL_SPACER_Y = int(0.02 * SCREEN_HEIGHT)

BIG_SPACER_X = int(0.1 * SCREEN_WIDTH)
BIG_SPACER_Y = int(0.1 * SCREEN_HEIGHT)

DIALOGUE_BOX_WIDTH = int(0.55 * SCREEN_WIDTH)
DIALOGUE_BOX_HEIGHT = int(0.2 * SCREEN_HEIGHT)

# Sub Screen settings
SUB_SCREEN_X = int(0.1 * SCREEN_WIDTH)
SUB_SCREEN_Y = int(0.06 * SCREEN_HEIGHT)

SCROLL_TEXT_COLOR = (20, 20, 20)
SCROLL_TEXT_X = int(0.16 * SCREEN_WIDTH)
SCROLL_TEXT_Y = int(0.34 * SCREEN_HEIGHT)
SCROLL_TEXT_MAX_WIDTH = int(0.13 * SCREEN_WIDTH)


SUB_SCREEN_BACKGROUND_IMG_PATH = 'img/sub_screen/background_bright.png'
SUB_BOX_BACKGROUND_IMG_PATH = 'img/sub_screen/background_dark.png'
SUB_SCREEN_BUTTON_IMG_PATH = 'img/sub_screen/button1.png'
SUB_BOX_SCROLL_BACKGROUND_IMG_PATH = 'img/sub_screen/scroll.png'
SUB_SCREEN_BACKGROUND_COLOR = (40, 40, 40)
SUB_SCREEN_BUTTON_TEXT_COLOR_ACTIVE = (252, 252, 121)
SUB_SCREEN_BUTTON_TEXT_COLOR_PASSIVE = (20, 20, 20)
SUB_SCREEN_BUTTON_TEXT_COLOR_HOVERED = (252, 252, 121)
SUB_SCREEN_BACKGROUND_TRANSPARENCY = 200
SUB_SCREEN_BACKGROUND_IMG_WIDTH = int(0.8 * SCREEN_WIDTH)
SUB_SCREEN_BACKGROUND_IMG_HEIGHT = int(0.68 * SCREEN_HEIGHT)
SUB_SCREEN_BUTTON_WIDTH = int(0.08 * SCREEN_WIDTH)
SUB_SCREEN_BUTTON_HEIGHT = int(0.05 * SCREEN_HEIGHT)
SUB_SCREEN_BUTTON_DELTA_X = int(0.09 * SCREEN_WIDTH)

MINI_CARD_WIDTH = int(0.02 * SCREEN_WIDTH)
MINI_CARD_HEIGHT = int(0.04 * SCREEN_HEIGHT)

