# Screen settings
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
SCREEN_CAPTION = 'Nepal Kings'

# Sizes
CENTER_X = int(0.5 * SCREEN_WIDTH)
CENTER_Y = int(0.5 * SCREEN_HEIGHT)

BUTTON_WIDTH = int(0.2 * SCREEN_WIDTH)
BUTTON_HEIGHT = int(0.06 * SCREEN_HEIGHT)

CONTROL_BUTTON_WIDTH = int(0.15 * SCREEN_WIDTH)
CONTROL_BUTTON_HEIGHT = int(0.04 * SCREEN_HEIGHT)

SMALL_FIELD_WIDTH = int(0.375 * SCREEN_WIDTH)
SMALL_FIELD_HEIGHT = int(0.05 * SCREEN_HEIGHT)

MESSAGE_SPACING = int(0.04 * SCREEN_HEIGHT)

TINY_SPACER_X = int(0.01 * SCREEN_WIDTH)
TINY_SPACER_Y = int(0.01 * SCREEN_HEIGHT)

SMALL_SPACER_X = int(0.02 * SCREEN_WIDTH)
SMALL_SPACER_Y = int(0.02 * SCREEN_HEIGHT)

BIG_SPACER_X = int(0.1 * SCREEN_WIDTH)
BIG_SPACER_Y = int(0.1 * SCREEN_HEIGHT)

DIALOGUE_BOX_WIDTH = int(0.55 * SCREEN_WIDTH)
DIALOGUE_BOX_HEIGHT = int(0.2 * SCREEN_HEIGHT)