# Copyright (c) 2026 Marc Stieffenhofer. All rights reserved.
# See LICENSE file in the project root for full license information.
from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT, _FS, _IS_MOBILE
from config.font_settings import FS_BODY, FS_SMALL, FS_TINY

# PATHS
SPELL_ICON_IMG_DIR = 'img/spells/icons/'
SPELL_ICON_GREYSCALE_IMG_DIR = 'img/spells/icons_greyscale/'
SPELL_FRAME_IMG_DIR = 'img/spells/frames/'
SPELL_FRAME_GREYSCALE_IMG_DIR = 'img/spells/frames_greyscale/'
SPELL_FRAME_HIDDEN_IMG_DIR = 'img/spells/frames_hidden/'
SPELL_GLOW_IMG_DIR = 'img/game_button/glow/'

# SPELL ICON DIMENSIONS (match build figure icon dimensions)
SPELL_ICON_WIDTH = int(0.05 * SCREEN_WIDTH)
SPELL_ICON_HEIGHT = int(0.05 * SCREEN_WIDTH)
SPELL_ICON_BIG_WIDTH = int(0.06 * SCREEN_WIDTH)
SPELL_ICON_BIG_HEIGHT = int(0.06 * SCREEN_WIDTH)

# SPELL ICON SCALING
SPELL_ICON_BIG_SCALE = 1.2
SPELL_FRAME_SCALE = 1.4

# SPELL ICON POSITIONING (layout in main display area)
SPELL_ICON_DELTA_X = int(0.105 * SCREEN_WIDTH)
SPELL_ICON_DELTA_Y = int(0.16 * SCREEN_HEIGHT)

# CAST SPELL SCREEN LAYOUT (match build figure screen layout)
CAST_SPELL_ICON_START_X = int(0.41 * SCREEN_WIDTH)
CAST_SPELL_ICON_START_Y = int(0.22 * SCREEN_HEIGHT)
CAST_SPELL_ICONS_PER_ROW = 6

# SPELL INFO BOX (match build figure info box)
CAST_SPELL_INFO_BOX_X = int(0.335 * SCREEN_WIDTH)
CAST_SPELL_INFO_BOX_Y = int(0.09 * SCREEN_HEIGHT)
CAST_SPELL_INFO_BOX_WIDTH = int(0.56 * SCREEN_WIDTH)
CAST_SPELL_INFO_BOX_HEIGHT = int(0.57 * SCREEN_HEIGHT)

# SPELL INFO BOX SCROLL (match build figure scroll area)
CAST_SPELL_INFO_BOX_SCROLL_X = int(0.15 * SCREEN_WIDTH)
CAST_SPELL_INFO_BOX_SCROLL_Y = int(0.15 * SCREEN_HEIGHT)
CAST_SPELL_INFO_BOX_SCROLL_WIDTH = int(0.18 * SCREEN_WIDTH)
CAST_SPELL_INFO_BOX_SCROLL_HEIGHT = int(0.44 * SCREEN_HEIGHT)

# SCROLL TEXT POSITIONING
CAST_SPELL_SCROLL_TEXT_X = int(0.166 * SCREEN_WIDTH)
CAST_SPELL_SCROLL_TEXT_Y = int(0.22 * SCREEN_HEIGHT)

# CONFIRM BUTTON (match build figure confirm button)
CAST_SPELL_CONFIRM_BUTTON_X = int(0.194 * SCREEN_WIDTH)
CAST_SPELL_CONFIRM_BUTTON_Y = int(0.62 * SCREEN_HEIGHT)

# SPELL TYPES
SPELL_TYPE_GREED = 'greed'  # Hand card manipulation (draw, exchange, discard)
SPELL_TYPE_ENCHANTMENT = 'enchantment'  # Attach to a figure
SPELL_TYPE_TACTICS = 'tactics'  # Modify battle type

# SPELL TYPE LABELS
SPELL_TYPE_LABEL_X = int(0.350 * SCREEN_WIDTH)
SPELL_TYPE_LABEL_Y_OFFSET = int(0.0 * SCREEN_HEIGHT)  # Vertical offset from icon position
SPELL_TYPE_LABEL_FONT_SIZE = int(FS_TINY * 1.1) if _IS_MOBILE else int(FS_BODY * 1.09)  # was int(0.024 * _FS)
SPELL_TYPE_LABEL_COLOR = (95, 42, 22)

# FONT SETTINGS
SPELL_ICON_FONT_SIZE = int(FS_TINY * 0.9) if _IS_MOBILE else int(FS_SMALL * 0.9)  # was int(0.018 * _FS)
SPELL_ICON_FONT_BIG_SIZE = int(0.022 * SCREEN_HEIGHT)
SPELL_ICON_CAPTION_COLOR = (95, 42, 22)

# GLOW SETTINGS
SPELL_ICON_GLOW_WIDTH = int(0.08 * SCREEN_WIDTH)
SPELL_ICON_GLOW_BIG_WIDTH = int(0.11 * SCREEN_WIDTH)

# BATTLE SPELL BOX (panel that wraps the battle modifier icons)
BATTLE_SPELL_BOX_Y_OFFSET = int(0.012 * SCREEN_HEIGHT)   # Gap below InfoScroll
BATTLE_SPELL_BOX_PADDING = int(0.008 * SCREEN_WIDTH)      # Inner padding around icons
BATTLE_SPELL_BOX_TITLE_MARGIN = int(0.008 * SCREEN_HEIGHT) # Space above title text
BATTLE_SPELL_BOX_TITLE_SPACING = int(0.005 * SCREEN_HEIGHT) # Space between title and icons
BATTLE_SPELL_BOX_BG_CLR = (35, 30, 25, 200)
BATTLE_SPELL_BOX_BORDER_CLR = (140, 130, 110)
BATTLE_SPELL_BOX_BORDER_WIDTH = 1
BATTLE_SPELL_BOX_CORNER_R = int(0.008 * SCREEN_HEIGHT)
BATTLE_SPELL_BOX_TITLE_COLOR = (250, 221, 0)
BATTLE_SPELL_BOX_TITLE_FONT_SIZE = int(FS_TINY * 0.94)     # was int(0.016 * _FS)  →  0.017 * 0.94 ≈ 0.016

# BATTLE MODIFIER ICON SETTINGS (inside the spell box)
BATTLE_MODIFIER_ICON_SIZE = int(0.035 * SCREEN_WIDTH)
BATTLE_MODIFIER_ICON_PADDING = int(0.005 * SCREEN_WIDTH)
