from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT

STATE_BUTTON_SYMBOL_IMG_PATH = 'img/status_icons/'
STATE_BUTTON_GLOW_IMG_PATH = 'img/game_button/glow/'

STATE_BUTTON_SYMBOL_WIDTH = int(0.04 * SCREEN_WIDTH)
STATE_BUTTON_GLOW_WIDTH = int(0.05 * SCREEN_WIDTH)

STATE_BUTTON_TEXT_SHIFT_Y = int(0.06 * SCREEN_HEIGHT)

STATE_BUTTON_TEXT_COLOR_ACTIVE = (0, 160, 0)
STATE_BUTTON_TEXT_COLOR_PASSIVE = (160, 0, 0) #(20, 20, 20)
STATE_BUTTON_TEXT_COLOR_SHADOW = (20, 20, 20) #(250, 221, 0)


STATE_BUTTON_TURN_X = int(0.035 * SCREEN_WIDTH)
STATE_BUTTON_TURN_Y = int(0.22 * SCREEN_HEIGHT)

STATE_BUTTON_INVADER_X = int(0.085 * SCREEN_WIDTH)
STATE_BUTTON_INVADER_Y = int(0.22 * SCREEN_HEIGHT)
