# Copyright (c) 2026 Marc Stieffenhofer. All rights reserved.
# See LICENSE file in the project root for full license information.
from config.screen_settings import SCREEN_WIDTH, SCREEN_HEIGHT, _FS, _UI_SCALE

STATE_BUTTON_SYMBOL_IMG_PATH = 'img/status_icons/'
STATE_BUTTON_GLOW_IMG_PATH = 'img/game_button/glow/'

_SBM = 1.3 if _UI_SCALE > 1.0 else 1.0   # enlarge state icons on mobile
STATE_BUTTON_SYMBOL_WIDTH = int(0.04 * SCREEN_WIDTH * _SBM)
STATE_BUTTON_GLOW_WIDTH = int(0.05 * SCREEN_WIDTH * _SBM)

STATE_BUTTON_TEXT_SHIFT_Y = int(0.06 * SCREEN_HEIGHT)

STATE_BUTTON_TEXT_COLOR_ACTIVE = (0, 160, 0)
STATE_BUTTON_TEXT_COLOR_PASSIVE = (160, 0, 0) #(20, 20, 20)
STATE_BUTTON_TEXT_COLOR_SHADOW = (20, 20, 20) #(250, 221, 0)


STATE_BUTTON_TURN_X = int(0.06 * SCREEN_WIDTH)
_TURN_Y_NUDGE = int(0.015 * SCREEN_HEIGHT) if _UI_SCALE > 1.0 else 0
STATE_BUTTON_TURN_Y = int(0.29 * SCREEN_HEIGHT) + _TURN_Y_NUDGE

STATE_BUTTON_INVADER_X = int(0.085 * SCREEN_WIDTH)
STATE_BUTTON_INVADER_Y = int(0.22 * SCREEN_HEIGHT)

STATE_BUTTON_CEASEFIRE_X = int(0.035 * SCREEN_WIDTH)
STATE_BUTTON_CEASEFIRE_Y = int(0.22 * SCREEN_HEIGHT)

# TOOLTIP PILL SETTINGS (shared by state buttons & battle modifier hover)
TOOLTIP_BG_COLOR = (45, 35, 25)
TOOLTIP_BORDER_COLOR = (140, 130, 110)
TOOLTIP_BORDER_WIDTH = 1
TOOLTIP_CORNER_R = int(0.005 * SCREEN_HEIGHT)
TOOLTIP_PAD_X = int(0.008 * SCREEN_WIDTH)
TOOLTIP_PAD_Y = int(0.006 * SCREEN_HEIGHT)
TOOLTIP_TEXT_COLOR = (240, 232, 210)       # warm off-white
TOOLTIP_DOT_RADIUS = max(3, int(0.004 * SCREEN_HEIGHT))
TOOLTIP_DOT_ACTIVE_CLR = (60, 190, 60)    # green dot
TOOLTIP_DOT_PASSIVE_CLR = (190, 50, 50)   # red dot
TOOLTIP_DOT_SPACING = int(0.006 * SCREEN_WIDTH)
TOOLTIP_FONT_SIZE = int(0.017 * _FS * (1.25 if _UI_SCALE > 1.0 else 1.0))
TOOLTIP_OFFSET_X = int(0.01 * SCREEN_WIDTH)   # horizontal gap from icon edge
TOOLTIP_OFFSET_Y = int(0.005 * SCREEN_HEIGHT)  # vertical nudge
