# Copyright (c) 2026 Marc Stieffenhofer. All rights reserved.
# See LICENSE file in the project root for full license information.
"""Hex-grid map renderer for the Kingdom screen."""

import math
import os
import pygame
from config import settings
from game.components import hex_cosmetics, badge_cosmetics
import logging

logger = logging.getLogger('nk.components.hex_map')

# ── Flat-top hexagon helpers ────────────────────────────────────────────────

def _hex_corner(cx, cy, size, i):
    """Return the (x, y) of the *i*-th corner of a flat-top hex centred at (cx, cy)."""
    angle_rad = math.pi / 180 * (60 * i)
    return (cx + size * math.cos(angle_rad),
            cy + size * math.sin(angle_rad))


def _hex_corners(cx, cy, size):
    """Return list of 6 corner points for a flat-top hex."""
    return [_hex_corner(cx, cy, size, i) for i in range(6)]


def _edge_neighbour_coords(col, row):
    """Return neighbour coordinates for each hex edge in corner order.

    Edge ``i`` spans corner ``i`` to ``i + 1``. Coordinates use the same
    odd-q flat-top layout as the server-side kingdom component logic.
    """
    if col % 2 == 0:
        return [
            (col + 1, row),
            (col, row + 1),
            (col - 1, row),
            (col - 1, row - 1),
            (col, row - 1),
            (col + 1, row - 1),
        ]
    return [
        (col + 1, row + 1),
        (col, row + 1),
        (col - 1, row + 1),
        (col - 1, row),
        (col, row - 1),
        (col + 1, row),
    ]


def _owner_color(user_id):
    """Deterministic colour from *user_id* for owner tinting."""
    if user_id is None:
        return None
    h = hash(user_id) & 0xFFFFFF
    r = 80 + ((h >> 16) & 0xFF) % 150
    g = 80 + ((h >> 8) & 0xFF) % 150
    b = 80 + (h & 0xFF) % 150
    return (r, g, b)


def _suit_bonus_group(suit):
    """Return the semantic colour group for a suit bonus."""
    if suit in ('Spades', 'Clubs'):
        return 'blue'
    if suit in ('Hearts', 'Diamonds'):
        return 'green'
    if suit == 'Neutral':
        return 'neutral'
    return 'green'


def _tile_fill_color(tile):
    """Return the map fill colour for a tile's suit bonus and tier."""
    group = _suit_bonus_group(getattr(tile, 'suit_bonus_suit', None))
    tier = getattr(tile, 'tier', 1)
    return settings.HEX_SUIT_TIER_FILL.get(group, {}).get(
        tier,
        settings.HEX_TIER_FILL.get(tier, (100, 100, 100)),
    )


def _tile_border_color(tile):
    """Return the default border colour for a tile's suit bonus and tier."""
    group = _suit_bonus_group(getattr(tile, 'suit_bonus_suit', None))
    tier = getattr(tile, 'tier', 1)
    return settings.HEX_SUIT_TIER_BORDER.get(group, {}).get(
        tier,
        settings.HEX_TIER_BORDER.get(tier, settings.HEX_EMPTY_BORDER),
    )


def _star_points(cx, cy, outer_r, inner_r, points=5):
    """Return polygon points for a small vector star."""
    pts = []
    start = -math.pi / 2
    step = math.pi / points
    for i in range(points * 2):
        r = outer_r if i % 2 == 0 else inner_r
        a = start + i * step
        pts.append((cx + math.cos(a) * r, cy + math.sin(a) * r))
    return pts


def _draw_capped_line(surface, color, start, end, width):
    """Draw a thick anti-aliased line with round caps.

    The border skins are drawn after all hex fills, so this helper favours
    smooth local supersampling over raw ``pygame.draw.line``.  It avoids the
    jagged stair-steps that are especially visible on diagonal hex edges.
    """
    width = max(1, int(width or 1))
    scale = 2 if width >= 2 else 1
    pad = width + 3
    min_x = int(math.floor(min(start[0], end[0]) - pad))
    min_y = int(math.floor(min(start[1], end[1]) - pad))
    max_x = int(math.ceil(max(start[0], end[0]) + pad))
    max_y = int(math.ceil(max(start[1], end[1]) + pad))
    surf_w = max(1, max_x - min_x)
    surf_h = max(1, max_y - min_y)
    line_surf = pygame.Surface((surf_w * scale, surf_h * scale), pygame.SRCALPHA)
    local_start = (
        int(round((start[0] - min_x) * scale)),
        int(round((start[1] - min_y) * scale)),
    )
    local_end = (
        int(round((end[0] - min_x) * scale)),
        int(round((end[1] - min_y) * scale)),
    )
    scaled_w = max(1, width * scale)
    pygame.draw.line(line_surf, color, local_start, local_end, scaled_w)
    radius = max(1, scaled_w // 2)
    pygame.draw.circle(line_surf, color, local_start, radius)
    pygame.draw.circle(line_surf, color, local_end, radius)
    if scale > 1:
        line_surf = pygame.transform.smoothscale(line_surf, (surf_w, surf_h))
    surface.blit(line_surf, (min_x, min_y))


def _draw_surface_pattern(*_args, **_kwargs):
    """Deprecated stub kept only as a monkey-patch hook for legacy tests.

    Real cosmetic surface art is generated by ``hex_cosmetics.render_surface_art``.
    """
    return None


# ═══════════════════════════════════════════════════════════════════
#  HexTile — data object for a single hex
# ═══════════════════════════════════════════════════════════════════

class HexTile:
    """Lightweight data holder for a single hex on the map."""

    __slots__ = (
        'land_id', 'col', 'row', 'tier', 'gold_rate',
        'suit_bonus_suit', 'suit_bonus_value',
        'owner', 'owner_style', 'is_mine', 'defence_incomplete',
        'kingdom_component_id', 'kingdom_component_size', 'kingdom_level',
        'kingdom_tier_name', 'kingdom_bonuses', 'kingdom_name',
        'kingdom_id', 'kingdom_shield_remaining', 'kingdom_shield_reason',
        'kingdom_is_shielded',
        'conquer_cooldown_remaining', 'cx', 'cy',
    )

    def __init__(self, land_dict, cx, cy):
        self.land_id = land_dict['id']
        self.col = land_dict['col']
        self.row = land_dict['row']
        self.tier = land_dict['tier']
        self.gold_rate = land_dict['gold_rate']
        self.suit_bonus_suit = land_dict['suit_bonus_suit']
        self.suit_bonus_value = land_dict['suit_bonus_value']
        self.owner = land_dict.get('owner')
        self.owner_style = land_dict.get('owner_style') or {}
        self.is_mine = land_dict.get('is_mine', False)
        self.defence_incomplete = land_dict.get('defence_incomplete', False)
        self.kingdom_component_id = land_dict.get('kingdom_component_id')
        self.kingdom_component_size = land_dict.get('kingdom_component_size', 0)
        self.kingdom_level = land_dict.get('kingdom_level', 0)
        self.kingdom_tier_name = land_dict.get('kingdom_tier_name')
        self.kingdom_bonuses = land_dict.get('kingdom_bonuses') or {}
        self.kingdom_name = land_dict.get('kingdom_name')
        self.kingdom_id = land_dict.get('kingdom_id')
        self.kingdom_shield_remaining = land_dict.get('kingdom_shield_remaining', 0) or 0
        self.kingdom_shield_reason = land_dict.get('kingdom_shield_reason')
        self.kingdom_is_shielded = bool(land_dict.get('kingdom_is_shielded', False))
        self.conquer_cooldown_remaining = land_dict.get(
            'conquer_cooldown_remaining', 0)
        self.cx = cx
        self.cy = cy

    @property
    def owner_user_id(self):
        return self.owner['user_id'] if self.owner else None

    @property
    def owner_username(self):
        return self.owner['username'] if self.owner else None


# ═══════════════════════════════════════════════════════════════════
#  HexMap — the main renderable hex grid
# ═══════════════════════════════════════════════════════════════════

class HexMap:
    """Flat-top hex grid with camera pan / zoom and minimap.

    Coordinate system: odd-column offset.
      pixel_x = col * 1.5 * size
      pixel_y = row * sqrt(3) * size + (col % 2) * sqrt(3)/2 * size
    """

    def __init__(self, lands_data, window, viewport_rect=None):
        self.window = window
        self._size = settings.HEX_SIZE
        self._border_w = settings.HEX_BORDER_W
        self.viewport_rect = pygame.Rect(
            viewport_rect or (0, 0, settings.SCREEN_WIDTH, settings.SCREEN_HEIGHT)
        )

        # Camera state (world coordinates, before zoom)
        self.camera_x = 0.0
        self.camera_y = 0.0
        self.zoom = 1.0

        # Drag state
        self._dragging = False
        self._drag_start = None
        self._drag_cam_start = None
        self._did_drag = False

        # Hover / selection
        self.hovered_tile = None
        self.selected_tile = None

        # Build tiles
        self.tiles = []
        self._tile_by_coord = {}
        self._world_min_x = 0.0
        self._world_max_x = 0.0
        self._world_min_y = 0.0
        self._world_max_y = 0.0
        self._build_tiles(lands_data)

        # Pre-load suit icons as raw surfaces and scale lazily per size.
        self._suit_icon_raw = {}
        self._scaled_icon_cache = {}
        for suit, path in settings.SUIT_ICON_PATHS.items():
            try:
                self._suit_icon_raw[suit] = pygame.image.load(path).convert_alpha()
            except Exception:
                logger.warning(f'Could not load suit icon: {path}')

        # Pre-load gold icon as raw surface and scale lazily per size.
        self._gold_icon_raw = None
        try:
            gold_icon_path = getattr(
                settings,
                'HEX_GOLD_ICON_PATH',
                settings.GAME_MENU_GOLD_ICON_PATH,
            )
            self._gold_icon_raw = pygame.image.load(
                gold_icon_path).convert_alpha()
        except Exception:
            logger.warning('Could not load gold icon for hex map')

        # Pre-load broken/warning icon for incomplete defences
        # Load at higher resolution to avoid blurriness when scaled up on tiles
        self._broken_icon_raw = None
        self._broken_icon = None
        try:
            broken_path = os.path.join(
                os.path.dirname(os.path.dirname(os.path.dirname(
                    os.path.abspath(__file__)))),
                'img', 'figures', 'state_icons', 'broken.png')
            self._broken_icon_raw = pygame.image.load(broken_path).convert_alpha()
            self._broken_icon = self._broken_icon_raw
        except Exception:
            logger.warning('Could not load broken icon for hex map')

        self._shield_icon_raw = None
        try:
            # Hex map uses a richer shield art than the in-battle block
            # icon — load it directly so we keep the battle icon path
            # untouched for other consumers.
            hex_shield_path = os.path.join(
                os.path.dirname(os.path.dirname(os.path.dirname(
                    os.path.abspath(__file__)))),
                'img', 'kingdom', 'skill_icons', 'shield.png')
            self._shield_icon_raw = pygame.image.load(
                hex_shield_path).convert_alpha()
        except Exception:
            try:
                shield_path = os.path.join(settings.RESOURCE_BASE,
                                           settings.KINGDOM_SHIELD_ICON_PATH)
                self._shield_icon_raw = pygame.image.load(
                    shield_path).convert_alpha()
            except Exception:
                logger.warning('Could not load kingdom shield icon for hex map')

        # Fonts
        self._label_font = settings.get_font(settings.HEX_LABEL_FONT_SIZE)
        self._tier_font = settings.get_font(settings.HEX_LABEL_FONT_SIZE, bold=True)

        # Centre camera on the grid
        self._centre_camera()

    def _get_scaled_icon(self, cache_key, raw_icon, icon_sz):
        """Return a cached icon surface at icon_sz with crisper downscaling."""
        if not raw_icon or icon_sz <= 0:
            return None
        k = (cache_key, int(icon_sz))
        cached = self._scaled_icon_cache.get(k)
        if cached is not None:
            return cached
        src_w, src_h = raw_icon.get_size()
        # Nearest-neighbour downscale keeps tiny UI icons sharper.
        if icon_sz <= min(src_w, src_h):
            scaled = pygame.transform.scale(raw_icon, (icon_sz, icon_sz))
        else:
            scaled = pygame.transform.smoothscale(raw_icon, (icon_sz, icon_sz))
        self._scaled_icon_cache[k] = scaled
        return scaled

    def _owner_style_key(self, tile, field_name):
        style = getattr(tile, 'owner_style', None) or {}
        default_style = getattr(settings, 'HEX_DEFAULT_OWNER_STYLE', {})
        return style.get(field_name) or default_style.get(field_name)

    def _same_owner_neighbour(self, tile, coord):
        neighbour = self._tile_by_coord.get(coord)
        return bool(neighbour and tile.owner_user_id and
                    neighbour.owner_user_id == tile.owner_user_id)

    # ── Grid construction ───────────────────────────────────────────

    def _build_tiles(self, lands_data):
        """Build HexTile objects with world-space centre positions."""
        self.tiles = []
        self._tile_by_coord = {}
        s = self._size
        for ld in lands_data:
            col, row = ld['col'], ld['row']
            cx = col * 1.5 * s
            cy = row * math.sqrt(3) * s + (col % 2) * math.sqrt(3) / 2 * s
            tile = HexTile(ld, cx, cy)
            self.tiles.append(tile)
            self._tile_by_coord[(tile.col, tile.row)] = tile
        self._update_world_bounds()

    def _update_world_bounds(self):
        """Cache world bounds including hex extents for camera clamping."""
        if not self.tiles:
            self._world_min_x = 0.0
            self._world_max_x = 0.0
            self._world_min_y = 0.0
            self._world_max_y = 0.0
            return
        self._world_min_x = min(t.cx for t in self.tiles) - self._size
        self._world_max_x = max(t.cx for t in self.tiles) + self._size
        self._world_min_y = min(t.cy for t in self.tiles) - self._size
        self._world_max_y = max(t.cy for t in self.tiles) + self._size

    def _clamp_camera(self):
        """Clamp camera so viewport cannot be dragged beyond map borders."""
        if not self.tiles:
            return

        min_wx = self._world_min_x
        max_wx = self._world_max_x
        min_wy = self._world_min_y
        max_wy = self._world_max_y

        world_w = max_wx - min_wx
        world_h = max_wy - min_wy
        view_w = self.viewport_rect.w / self.zoom
        view_h = self.viewport_rect.h / self.zoom

        if view_w >= world_w:
            self.camera_x = min_wx - (view_w - world_w) / 2.0
        else:
            self.camera_x = max(min_wx, min(self.camera_x, max_wx - view_w))

        if view_h >= world_h:
            self.camera_y = min_wy - (view_h - world_h) / 2.0
        else:
            self.camera_y = max(min_wy, min(self.camera_y, max_wy - view_h))

    def _centre_camera(self):
        """Set camera so the grid is centred in the viewport."""
        if not self.tiles:
            return
        min_x = min(t.cx for t in self.tiles)
        max_x = max(t.cx for t in self.tiles)
        min_y = min(t.cy for t in self.tiles)
        max_y = max(t.cy for t in self.tiles)
        grid_cx = (min_x + max_x) / 2
        grid_cy = (min_y + max_y) / 2
        vw = self.viewport_rect.w
        vh = self.viewport_rect.h
        self.camera_x = grid_cx - vw / (2 * self.zoom)
        self.camera_y = grid_cy - vh / (2 * self.zoom)
        self._clamp_camera()

    def set_viewport(self, viewport_rect):
        """Set the screen-space viewport used for render clipping and input gating."""
        self.viewport_rect = pygame.Rect(viewport_rect)
        self._clamp_camera()

    # ── Coordinate transforms ──────────────────────────────────────

    def world_to_screen(self, wx, wy):
        """Convert world coordinates to screen pixel coordinates."""
        sx = self.viewport_rect.x + (wx - self.camera_x) * self.zoom
        sy = self.viewport_rect.y + (wy - self.camera_y) * self.zoom
        return (sx, sy)

    def screen_to_world(self, sx, sy):
        """Convert screen pixel coordinates to world coordinates."""
        wx = (sx - self.viewport_rect.x) / self.zoom + self.camera_x
        wy = (sy - self.viewport_rect.y) / self.zoom + self.camera_y
        return (wx, wy)

    def _in_viewport(self, pos):
        return self.viewport_rect.collidepoint(pos)

    def _should_draw_land_info(self, sz):
        """Return whether tile info labels should be rendered at current zoom."""
        min_zoom = float(getattr(
            settings,
            'HEX_MAP_LAND_INFO_MIN_ZOOM',
            settings.HEX_MAP_ZOOM_MIN,
        ))
        return self.zoom >= min_zoom and sz >= 20

    def _zoom_at_screen_pos(self, sx, sy, zoom_delta):
        """Zoom around a screen-space point while keeping that world point anchored."""
        old_zoom = self.zoom
        wx, wy = self.screen_to_world(sx, sy)
        self.zoom = max(
            settings.HEX_MAP_ZOOM_MIN,
            min(settings.HEX_MAP_ZOOM_MAX, self.zoom + zoom_delta),
        )
        if self.zoom == old_zoom:
            return

        local_x = sx - self.viewport_rect.x
        local_y = sy - self.viewport_rect.y
        self.camera_x = wx - local_x / self.zoom
        self.camera_y = wy - local_y / self.zoom
        self._clamp_camera()

    def is_drag_release(self, event):
        """Return True if *event* is the release of an active drag gesture."""
        return bool(
            event.type == pygame.MOUSEBUTTONUP
            and getattr(event, 'button', None) == 1
            and self._dragging
            and self._did_drag
        )

    # ── Hit testing ─────────────────────────────────────────────────

    def tile_at_screen_pos(self, sx, sy):
        """Return the HexTile under screen position (sx, sy), or None."""
        wx, wy = self.screen_to_world(sx, sy)
        best = None
        best_dist = float('inf')
        sz = self._size
        # Quick radius check (hex inscribed circle radius = size * sqrt(3)/2)
        max_r = sz
        for tile in self.tiles:
            dx = wx - tile.cx
            dy = wy - tile.cy
            dist = math.sqrt(dx * dx + dy * dy)
            if dist < max_r and dist < best_dist:
                best = tile
                best_dist = dist
        return best

    # ── Event handling ──────────────────────────────────────────────

    def handle_event(self, event):
        """Process a single pygame event. Returns clicked HexTile or None."""
        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            if not self._in_viewport(event.pos):
                return None
            self._dragging = True
            self._drag_start = event.pos
            self._drag_cam_start = (self.camera_x, self.camera_y)
            self._did_drag = False
            return None

        if event.type == pygame.MOUSEMOTION:
            # Update hover
            if self._in_viewport(event.pos):
                self.hovered_tile = self.tile_at_screen_pos(*event.pos)
            else:
                self.hovered_tile = None
            # Handle drag
            if self._dragging and self._drag_start:
                dx = event.pos[0] - self._drag_start[0]
                dy = event.pos[1] - self._drag_start[1]
                if abs(dx) > settings.HEX_MAP_DRAG_THRESHOLD or \
                   abs(dy) > settings.HEX_MAP_DRAG_THRESHOLD:
                    self._did_drag = True
                if self._did_drag:
                    self.camera_x = self._drag_cam_start[0] - dx / self.zoom
                    self.camera_y = self._drag_cam_start[1] - dy / self.zoom
                    self._clamp_camera()
            return None

        if event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            was_drag = self._did_drag
            self._dragging = False
            self._drag_start = None
            self._drag_cam_start = None
            self._did_drag = False
            if not was_drag:
                if not self._in_viewport(event.pos):
                    return None
                clicked = self.tile_at_screen_pos(*event.pos)
                if clicked:
                    self.selected_tile = clicked
                    return clicked
            return None

        if event.type == pygame.MOUSEWHEEL:
            # Zoom centred on cursor
            mx, my = pygame.mouse.get_pos()
            if not self._in_viewport((mx, my)):
                return None
            if event.y > 0:
                self._zoom_at_screen_pos(mx, my, settings.HEX_MAP_ZOOM_STEP)
            elif event.y < 0:
                self._zoom_at_screen_pos(mx, my, -settings.HEX_MAP_ZOOM_STEP)
            return None

        return None

    # ── Zoom via navigation buttons ─────────────────────────────────

    def zoom_in(self):
        cx, cy = self.viewport_rect.center
        self._zoom_at_screen_pos(cx, cy, settings.HEX_MAP_ZOOM_STEP)

    def zoom_out(self):
        cx, cy = self.viewport_rect.center
        self._zoom_at_screen_pos(cx, cy, -settings.HEX_MAP_ZOOM_STEP)

    def pan(self, dx_world, dy_world):
        self.camera_x += dx_world
        self.camera_y += dy_world
        self._clamp_camera()

    # ── Rendering ───────────────────────────────────────────────────

    def render(self):
        """Draw all visible hexes, labels, and minimap."""
        sz = self._size * self.zoom
        vp = self.viewport_rect

        old_clip = self.window.get_clip()
        self.window.set_clip(vp)

        visible_hexes = []
        for tile in self.tiles:
            scx, scy = self.world_to_screen(tile.cx, tile.cy)

            # Frustum culling
            if scx < vp.left - sz * 2 or scx > vp.right + sz * 2:
                continue
            if scy < vp.top - sz * 2 or scy > vp.bottom + sz * 2:
                continue

            corners = _hex_corners(scx, scy, sz)
            visible_hexes.append((tile, corners, scx, scy))

        # Layered rendering fixes borders being overwritten by neighbouring
        # hex fills (most visible on lower/right edges with thick skins).
        for tile, corners, scx, scy in visible_hexes:
            self._draw_hex_base(tile, corners, scx, scy, sz)
        for tile, corners, scx, scy in visible_hexes:
            self._draw_hex_border(tile, corners)
        for tile, corners, scx, scy in visible_hexes:
            self._draw_hex_details(tile, scx, scy, sz)

        # Suit cluster icons (drawn before kingdom badges so the kingdom
        # name pill always sits on top of the suit icon).
        self._draw_suit_cluster_icons(sz)
        self._draw_kingdom_badges(sz)

        self.window.set_clip(old_clip)

        self._draw_minimap()

    def _draw_hex(self, tile, corners, scx, scy, sz):
        """Draw a single hex with fill, border, and labels."""
        self._draw_hex_base(tile, corners, scx, scy, sz)
        self._draw_hex_border(tile, corners)
        self._draw_hex_details(tile, scx, scy, sz)

    def _draw_hex_base(self, tile, corners, scx, scy, sz):
        """Draw glow, fill, and owned-land surface cosmetics."""
        # Fill colour follows suit-bonus colour; tier controls intensity.
        fill = list(_tile_fill_color(tile))

        # Hover brighten
        if tile is self.hovered_tile:
            b = settings.HEX_HOVER_BRIGHTEN
            fill = [min(255, c + b) for c in fill]

        if tile.is_mine:
            xs = [p[0] for p in corners]
            ys = [p[1] for p in corners]
            glow_rect = pygame.Rect(
                int(min(xs)) - 4,
                int(min(ys)) - 4,
                int(max(xs) - min(xs)) + 8,
                int(max(ys) - min(ys)) + 8,
            )
            glow_surf = pygame.Surface((glow_rect.w, glow_rect.h), pygame.SRCALPHA)
            local_corners = [(x - glow_rect.x, y - glow_rect.y) for x, y in corners]
            soft_local = [
                (x - glow_rect.x + (x - scx) * 0.10,
                 y - glow_rect.y + (y - scy) * 0.10)
                for x, y in corners
            ]
            pygame.draw.polygon(glow_surf, settings.HEX_MINE_GLOW_SOFT_CLR, soft_local)
            pygame.draw.polygon(glow_surf, settings.HEX_MINE_GLOW_CLR, local_corners)
            self.window.blit(glow_surf, glow_rect.topleft)

        pygame.draw.polygon(self.window, fill, corners)

        if tile.owner:
            self._draw_surface_skin(tile, corners, scx, scy, sz)

    def _draw_hex_border(self, tile, corners):
        """Draw selection and border cosmetics after all hex fills."""
        if tile.owner:
            self._draw_owner_border(tile, corners)
            if tile is self.selected_tile:
                pygame.draw.polygon(self.window, settings.HEX_SELECT_BORDER, corners,
                                    max(1, int((self._border_w + 1) * self.zoom)))
        else:
            border_clr = _tile_border_color(tile)
            bw = self._border_w
            pygame.draw.polygon(self.window, border_clr, corners,
                                max(1, int(bw * self.zoom / 1.0)))
            if tile is self.selected_tile:
                pygame.draw.polygon(self.window, settings.HEX_SELECT_BORDER, corners,
                                    max(1, int((self._border_w + 1) * self.zoom)))

    def _draw_hex_details(self, tile, scx, scy, sz):
        """Draw the per-tile overlays.

        Layout (high zoom):
          - top edge:      tier stars (no frame), straddling the flat top
          - centre:        suit icon with the bonus number on top
          - bottom-centre: core/timed shield (when shielded)
          - bottom edge:   owner chip (badge cosmetic + colored dot + name)
          - top-right:     pulsing warning badge (if defences incomplete)

        At low zoom per-tile suit icon is suppressed; a single suit icon
        is rendered at the cluster centre and a single name badge is
        rendered below it by ``_draw_kingdom_badges``.
        """
        zoom = self.zoom
        sz_ok_icons = (zoom >= settings.HEX_MAP_LAND_INFO_MIN_ZOOM
                       and sz >= 18)
        per_tile_suit = (zoom >= settings.HEX_MAP_LAND_NUMBERS_MIN_ZOOM
                         and sz >= 24)

        if sz_ok_icons:
            self._draw_tier_ribbon(tile, scx, scy, sz)

        if per_tile_suit:
            self._draw_center_suit(tile, scx, scy, sz)

        if tile.kingdom_is_shielded and sz > 24:
            self._draw_shield_badge(tile, scx, scy, sz)

        if tile.defence_incomplete and sz_ok_icons:
            self._draw_warning_badge(tile, scx, scy, sz,
                                     pygame.time.get_ticks())

        if tile is self.hovered_tile:
            self._draw_hover_ring(scx, scy, sz)

    # ── Pill / overlay helpers ─────────────────────────────────────

    def _draw_pill(self, rect, *, role='default'):
        """Render a rounded pill background+border. Returns the rect drawn."""
        bg = settings.HEX_PILL_BG_CLR
        if role == 'own':
            border = settings.HEX_PILL_BORDER_OWN
        elif role == 'warn':
            border = settings.HEX_WARNING_BORDER_CLR
        elif role == 'shield':
            border = (140, 190, 255)
        else:
            border = settings.HEX_PILL_BORDER_CLR
        radius = settings.HEX_PILL_RADIUS_PX
        cache = getattr(self, '_pill_cache', None)
        if cache is None:
            cache = {}
            self._pill_cache = cache
        key = (role, rect.w, rect.h)
        surf = cache.get(key)
        if surf is None:
            surf = pygame.Surface((rect.w, rect.h), pygame.SRCALPHA)
            pygame.draw.rect(surf, bg, surf.get_rect(), border_radius=radius)
            pygame.draw.rect(surf, border, surf.get_rect(), 1,
                             border_radius=radius)
            cache[key] = surf
        self.window.blit(surf, rect.topleft)
        return rect

    def _draw_tier_ribbon(self, tile, scx, scy, sz, *, y_offset=0):
        """One frameless star per tier level, centred on the hex's flat
        top edge so the stars visually click into the tile silhouette.
        No background pill — just stars + a soft drop shadow for legibility.
        """
        tier = max(1, min(4, int(getattr(tile, 'tier', 1) or 1)))
        star_r = max(4, int(sz * settings.HEX_TIER_RIBBON_STAR_SZ_FACTOR))
        inner_r = max(2, int(star_r * 0.5))
        gap = max(2, int(star_r * 0.6))
        total_w = tier * (star_r * 2) + (tier - 1) * gap
        # Top flat edge of the flat-top hex sits at y = scy - sz*sqrt(3)/2.
        # Nudge stars a touch inside the tile so they don't kiss the border.
        top_edge_y = int(scy - sz * (math.sqrt(3) / 2))
        edge_inset = max(1, int(sz * 0.14))
        cy = top_edge_y + edge_inset + int(y_offset)
        start_x = int(scx - total_w / 2) + star_r
        outline_w = 1 if star_r >= 5 else 0
        for i in range(tier):
            sx = start_x + i * (star_r * 2 + gap)
            shadow = _star_points(sx + 1, cy + 2, star_r, inner_r)
            pts = _star_points(sx, cy, star_r, inner_r)
            pygame.draw.polygon(self.window, (16, 12, 4), shadow)
            pygame.draw.polygon(self.window, settings.HEX_STAR_FILL, pts)
            if outline_w:
                pygame.draw.polygon(self.window, settings.HEX_STAR_BORDER,
                                    pts, outline_w)

    def _draw_center_suit(self, tile, scx, scy, sz):
        """Large centred suit icon with the bonus number rendered on top.

        Replaces the bottom stat strip: gold rate is now only shown in the
        land detail box. The bonus number is drawn without a leading ``+``
        per the latest design.
        """
        suit = getattr(tile, 'suit_bonus_suit', None)
        suit_raw = self._suit_icon_raw.get(suit)
        if suit_raw is None:
            return
        icon_sz = max(14, int(sz * 0.62))
        icon = self._get_scaled_icon(suit, suit_raw, icon_sz)
        if icon is None:
            return
        # Slight transparency so the suit doesn't overpower the tile fill.
        try:
            ghost = icon.copy()
            ghost.set_alpha(190)
            icon = ghost
        except Exception:
            pass
        rect = icon.get_rect(center=(int(scx), int(scy)))
        self.window.blit(icon, rect)

        bonus = int(getattr(tile, 'suit_bonus_value', 0) or 0)
        if bonus <= 0:
            return
        # Bonus number in a bold tier-style font, sized relative to icon.
        font_px = max(10, int(icon_sz * 0.55))
        font = settings.get_font(font_px, bold=True)
        text = font.render(str(bonus), True, (255, 244, 200))
        # Crisp dark outline for legibility on bright tile fills.
        outline = font.render(str(bonus), True, (24, 16, 4))
        cx_i, cy_i = int(scx), int(scy)
        for dx, dy in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            self.window.blit(outline,
                             outline.get_rect(center=(cx_i + dx, cy_i + dy)))
        self.window.blit(text, text.get_rect(center=(cx_i, cy_i)))

    def _draw_warning_badge(self, tile, scx, scy, sz, now_ms):
        """Pulsing red badge with the broken icon for incomplete defences.
        Anchored to the hex's top-right flat corner."""
        r = max(8, int(sz * 0.20))
        # Anchor to the top-right flat corner of the flat-top hex.
        cx = int(scx + sz * 0.50) - max(1, int(self.zoom))
        cy = int(scy - sz * (math.sqrt(3) / 2)) + r + max(1, int(self.zoom))
        phase = (now_ms / 1000.0) * settings.HEX_WARNING_PULSE_HZ * 2 * math.pi
        alpha = 200 + int(40 * math.sin(phase))
        alpha = max(160, min(240, alpha))
        bg = (*settings.HEX_WARNING_BG_CLR[:3], alpha)
        size = r * 2 + 4
        surf = pygame.Surface((size, size), pygame.SRCALPHA)
        pygame.draw.circle(surf, bg, (r + 2, r + 2), r)
        pygame.draw.circle(surf, settings.HEX_WARNING_BORDER_CLR,
                           (r + 2, r + 2), r, 1)
        if self._broken_icon_raw:
            icon_sz = max(6, int(r * 1.7))
            icon = self._get_scaled_icon('broken', self._broken_icon_raw,
                                          icon_sz)
            if icon is not None:
                surf.blit(icon, icon.get_rect(center=(r + 2, r + 2)))
        else:
            txt = self._tier_font.render('!', True,
                                          settings.HEX_WARNING_TEXT_CLR)
            surf.blit(txt, txt.get_rect(center=(r + 2, r + 2)))
        self.window.blit(surf, (cx - r - 2, cy - r - 2))

    def _draw_owner_chip(self, tile, scx, scy, sz, *, show_name):
        """Colored owner dot (+ truncated username) anchored on the bottom
        flat edge of the hex.

        The pill behind the name inherits the kingdom's equipped *badge*
        cosmetic so the player's identity is visually consistent across
        zoom levels.  The colored dot sits to the left of the badge
        surface and remains a quick suit-agnostic owner indicator.
        """
        dot_r = max(4, int(sz * settings.HEX_OWNER_CHIP_DOT_R_FACTOR))
        is_mine = tile.is_mine
        owner_clr = (settings.HEX_MINE_BORDER if is_mine
                     else (_owner_color(tile.owner_user_id) or (180, 180, 180)))
        font = self._label_font
        name = tile.owner_username or ''
        if is_mine:
            name = 'You'
        if show_name and name:
            max_text_w = max(20, int(sz * 1.4))
            # Truncate to the chip's text budget before sending to the
            # badge renderer so the cache keys cleanly per truncation.
            truncated = name
            if font.size(name)[0] > max_text_w:
                while truncated and font.size(truncated + '…')[0] > max_text_w:
                    truncated = truncated[:-1]
                truncated = (truncated + '…') if truncated else '…'
            badge_key = (self._owner_style_key(tile, 'badge_key')
                         or settings.HEX_BADGE_DEFAULT_KEY)
            target_h = font.get_height() + max(2, settings.HEX_PILL_PAD_Y * 2)
            shimmer_phase = badge_cosmetics.shimmer_phase_for(
                pygame.time.get_ticks())
            badge_surf = badge_cosmetics.render_badge(
                badge_key, truncated, font,
                target_h=target_h, shimmer_phase=shimmer_phase,
            )
        else:
            badge_surf = None

        gap = max(2, int(2 * self.zoom))
        badge_w = badge_surf.get_width() if badge_surf else 0
        badge_h = badge_surf.get_height() if badge_surf else dot_r * 2
        rect_w = dot_r * 2 + (gap + badge_w if badge_surf else 0)
        rect_h = max(dot_r * 2, badge_h)
        # Sit straddling the hex bottom edge: half above, half below, so
        # the chip visually clicks onto the tile boundary.
        y = int(scy + sz * (math.sqrt(3) / 2)) - rect_h // 2
        x = int(scx - rect_w / 2)
        mid_y = y + rect_h // 2
        pygame.draw.circle(self.window, owner_clr,
                           (x + dot_r, mid_y), dot_r)
        pygame.draw.circle(self.window, (12, 10, 8),
                           (x + dot_r, mid_y), dot_r, 1)
        if badge_surf:
            bx = x + dot_r * 2 + gap
            by = mid_y - badge_surf.get_height() // 2
            self.window.blit(badge_surf, (bx, by))

    def _draw_hover_ring(self, scx, scy, sz):
        """Thin white-alpha inner ring around the hovered hex."""
        inner_sz = max(4, sz - max(2, int(2 * self.zoom)))
        pts = _hex_corners(scx, scy, inner_sz)
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        min_x = int(min(xs)) - 2
        min_y = int(min(ys)) - 2
        max_x = int(max(xs)) + 2
        max_y = int(max(ys)) + 2
        surf = pygame.Surface((max_x - min_x, max_y - min_y),
                              pygame.SRCALPHA)
        local = [(p[0] - min_x, p[1] - min_y) for p in pts]
        pygame.draw.polygon(surf, settings.HEX_HOVER_RING_CLR, local,
                            settings.HEX_HOVER_RING_W)
        self.window.blit(surf, (min_x, min_y))

    # ── Suit clusters ──────────────────────────────────────────────

    def _suit_clusters(self):
        """Return one descriptor per connected component of same-suit tiles.

        Connectivity uses the same odd-q flat-top hex neighbour layout as
        the kingdom-component logic. Tiles without a suit bonus are
        skipped entirely.
        """
        coord_to_tile = {(t.col, t.row): t for t in self.tiles}
        visited = set()
        clusters = []
        for start in self.tiles:
            if start.land_id in visited:
                continue
            suit = getattr(start, 'suit_bonus_suit', None)
            if not suit:
                visited.add(start.land_id)
                continue
            stack = [start]
            members = []
            while stack:
                cur = stack.pop()
                if cur.land_id in visited:
                    continue
                if getattr(cur, 'suit_bonus_suit', None) != suit:
                    continue
                visited.add(cur.land_id)
                members.append(cur)
                for ncoord in _edge_neighbour_coords(cur.col, cur.row):
                    nb = coord_to_tile.get(ncoord)
                    if nb is None or nb.land_id in visited:
                        continue
                    if getattr(nb, 'suit_bonus_suit', None) == suit:
                        stack.append(nb)
            if not members:
                continue
            cx = sum(t.cx for t in members) / len(members)
            cy = sum(t.cy for t in members) / len(members)
            clusters.append({
                'suit': suit,
                'center_x': cx,
                'center_y': cy,
                'tile_count': len(members),
            })
        return clusters

    def _draw_suit_cluster_icons(self, sz):
        """Draw one large suit icon at the centre of every connected
        same-suit region. Only visible when zoomed out (per-tile suit
        icons are hidden); suppressed at high zoom."""
        if sz <= 8:
            return
        if self.zoom >= settings.HEX_MAP_LAND_NUMBERS_MIN_ZOOM:
            return
        vp = self.viewport_rect
        icon_sz = max(20, int(sz * 1.05))
        for cluster in self._suit_clusters():
            # Tiny single-tile clusters can rely on the per-tile icon at
            # higher zoom; skip the cluster overlay so it doesn't fight
            # with the regular tile fill.
            if cluster['tile_count'] < 2:
                continue
            scx, scy = self.world_to_screen(
                cluster['center_x'], cluster['center_y'])
            if scx < vp.left - 100 or scx > vp.right + 100:
                continue
            if scy < vp.top - 100 or scy > vp.bottom + 100:
                continue
            suit = cluster['suit']
            suit_raw = self._suit_icon_raw.get(suit)
            if suit_raw is None:
                continue
            icon = self._get_scaled_icon(
                f'cluster_{suit}', suit_raw, icon_sz)
            if icon is None:
                continue
            try:
                ghost = icon.copy()
                ghost.set_alpha(190)
                icon = ghost
            except Exception:
                pass
            self.window.blit(
                icon,
                icon.get_rect(center=(int(scx), int(scy))))

    def _kingdom_badges(self):
        """Return grouped badge descriptors for all visible owned kingdoms."""
        groups = {}
        for tile in self.tiles:
            if not tile.owner_user_id:
                continue

            if tile.kingdom_id is not None:
                group_key = ('kingdom', tile.kingdom_id)
            elif tile.kingdom_component_id is not None:
                group_key = ('component', tile.owner_user_id, tile.kingdom_component_id)
            else:
                # No persistent kingdom/component information available.
                # Keep per-tile owner labels as the fallback in this case.
                continue

            group = groups.setdefault(group_key, {
                'tiles': [],
                'name': None,
                'kingdom_id': tile.kingdom_id,
                'owner_username': tile.owner_username,
                'badge_keys': {},
                'suit_keys': {},
                'levels': {},
            })
            group['tiles'].append(tile)
            if not group['name']:
                name = str(tile.kingdom_name or '').strip()
                if name:
                    group['name'] = name
            try:
                level = int(getattr(tile, 'kingdom_level', 0) or 0)
            except (TypeError, ValueError):
                level = 0
            if level > 0:
                group['levels'][level] = group['levels'].get(level, 0) + 1
            bk = (self._owner_style_key(tile, 'badge_key')
                  or settings.HEX_BADGE_DEFAULT_KEY)
            group['badge_keys'][bk] = group['badge_keys'].get(bk, 0) + 1
            sk = getattr(tile, 'suit_bonus_suit', None)
            if sk:
                group['suit_keys'][sk] = group['suit_keys'].get(sk, 0) + 1

        badges = []
        for group in groups.values():
            tiles = group['tiles']
            if not tiles:
                continue
            center_x = sum(tile.cx for tile in tiles) / len(tiles)
            center_y = sum(tile.cy for tile in tiles) / len(tiles)
            name = group['name']
            if not name:
                if group['kingdom_id'] is not None:
                    name = f'Kingdom #{group["kingdom_id"]}'
                elif group.get('owner_username'):
                    name = str(group['owner_username'])
                else:
                    name = 'Kingdom'
            badge_key = (max(group['badge_keys'].items(),
                             key=lambda kv: kv[1])[0]
                         if group['badge_keys']
                         else settings.HEX_BADGE_DEFAULT_KEY)
            suit_key = (max(group['suit_keys'].items(), key=lambda kv: kv[1])[0]
                        if group['suit_keys'] else None)
            level = (max(group['levels'].items(), key=lambda kv: (kv[1], kv[0]))[0]
                     if group['levels'] else 0)
            subtitle = f'Lv {level}' if level > 0 else None
            badges.append({
                'name': name,
                'level': level,
                'subtitle': subtitle,
                'center_x': center_x,
                'center_y': center_y,
                'tile_count': len(tiles),
                'badge_key': badge_key,
                'suit_key': suit_key,
                'representative_tile': tiles[0],
            })
        return badges

    def _draw_kingdom_badges(self, sz):
        """Draw the kingdom name badge as a nameplate plinth below each
        owned cluster's suit icon.

        The badge background, ornaments and text are produced as a single
        cached surface by ``badge_cosmetics.render_badge`` so per-frame
        cost is one ``blit`` per visible kingdom.
        """
        # Allow the kingdom name to show even when zoomed all the way out
        # — it's the most useful low-zoom information.
        if sz <= 8:
            return
        if self.zoom >= settings.HEX_MAP_OWNER_NAME_MIN_ZOOM:
            return

        vp = self.viewport_rect
        font = self._label_font
        subtitle_font = settings.get_font(
            max(8, int(font.get_height() * 0.68)), bold=True)
        offset_y = sz * settings.HEX_GROUP_BADGE_OFFSET_Y
        gap_px = max(1, int(sz * settings.HEX_GROUP_BADGE_GAP_FACTOR))
        subtitle_h = subtitle_font.get_height()
        target_h = max(font.get_height() + subtitle_h + 8,
                       int((font.get_height() + subtitle_h) * 1.25))
        # Suit cluster icon footprint (matches _draw_suit_cluster_icons).
        cluster_icon_sz = max(20, int(sz * 1.05))
        shimmer_phase = badge_cosmetics.shimmer_phase_for(
            pygame.time.get_ticks())

        for badge_data in self._kingdom_badges():
            cx_w, cy_w = badge_data['center_x'], badge_data['center_y']
            scx, scy = self.world_to_screen(cx_w, cy_w)
            # Keep cluster rendering scoped to visible map area.
            if scx < vp.left - 100 or scx > vp.right + 100:
                continue
            if scy < vp.top - 60 or scy > vp.bottom + 100:
                continue

            badge_key = (badge_data.get('badge_key')
                         or settings.HEX_BADGE_DEFAULT_KEY)
            subtitle = badge_data.get('subtitle')
            if subtitle:
                badge_surf = badge_cosmetics.render_badge_with_subtitle(
                    badge_key,
                    str(badge_data['name']),
                    str(subtitle),
                    font,
                    subtitle_font=subtitle_font,
                    target_h=target_h,
                    shimmer_phase=shimmer_phase,
                )
            else:
                badge_surf = badge_cosmetics.render_badge(
                    badge_key,
                    str(badge_data['name']),
                    font,
                    target_h=target_h,
                    shimmer_phase=shimmer_phase,
                )

            # Anchor the badge below the suit cluster icon.
            label_y = scy + offset_y + cluster_icon_sz * 0.55 + gap_px
            br = badge_surf.get_rect(center=(int(scx), int(label_y)))

            shadow_dx, shadow_dy = settings.HEX_GROUP_BADGE_SHADOW_OFFSET
            shadow_radius = max(2, int(3 * self.zoom))
            shadow = self._shadow_for(badge_surf.get_size(), shadow_radius)
            self.window.blit(shadow,
                             (br.x + shadow_dx, br.y + shadow_dy))
            self.window.blit(badge_surf, br)

    def _shadow_for(self, size, radius):
        """Return a cached drop-shadow surface for the given pixel size."""
        cache = getattr(self, '_badge_shadow_cache', None)
        if cache is None:
            cache = {}
            self._badge_shadow_cache = cache
        key = (size, radius)
        surf = cache.get(key)
        if surf is None:
            surf = pygame.Surface(size, pygame.SRCALPHA)
            pygame.draw.rect(surf, settings.HEX_GROUP_BADGE_SHADOW_CLR,
                             surf.get_rect(), border_radius=radius)
            # Bound cache so it never grows without limit.
            if len(cache) > 32:
                cache.pop(next(iter(cache)))
            cache[key] = surf
        return surf

    def _format_countdown(self, seconds):
        if int(seconds or 0) < 0:
            return 'Core'
        seconds = max(0, int(seconds or 0))
        if seconds >= 3600:
            return f'{seconds // 3600}h'
        if seconds >= 60:
            return f'{seconds // 60}m'
        return f'{seconds}s'

    def _draw_shield_badge(self, tile, scx, scy, sz):
        """Shield icon anchored at the lower bottom-center of the hex.

        Core kingdoms (``remaining < 0``) are permanently shielded; the
        shield is drawn without a number. Timed shields overlay the
        remaining time *on top* of the shield (centred over the icon).
        """
        remaining = int(tile.kingdom_shield_remaining or 0)
        is_core = remaining < 0
        # Larger than before so the shield reads clearly and a number can
        # sit legibly on top of it.
        icon_sz = max(20, int(sz * (0.55 if is_core else 0.50)))
        cx = int(scx)
        # Bottom of icon sits slightly above the hex bottom edge.
        bottom_y = int(round(scy + sz * (math.sqrt(3) / 2) - sz * 0.10))
        icon_center = (cx, bottom_y - icon_sz // 2)
        if self._shield_icon_raw:
            icon = self._get_scaled_icon('shield', self._shield_icon_raw,
                                         icon_sz)
            if icon is not None:
                rect = icon.get_rect(midbottom=(cx, bottom_y))
                icon_center = rect.center
                self.window.blit(icon, rect)
        else:
            r = icon_sz // 2
            cy = icon_center[1]
            pygame.draw.polygon(self.window, (140, 190, 255), [
                (cx, cy - r),
                (cx + r, cy - r // 3),
                (cx, cy + r),
                (cx - r, cy - r // 3),
            ])
        if is_core:
            return
        # Overlay the remaining duration *on top* of the shield, slightly
        # below centre so it visually sits inside the shield's body.
        label = self._format_countdown(remaining)
        font_px = max(10, int(icon_sz * 0.42))
        font = settings.get_font(font_px, bold=True)
        txt = font.render(label, True, (255, 248, 220))
        outline = font.render(label, True, (16, 12, 4))
        center = (icon_center[0], icon_center[1] + int(icon_sz * 0.05))
        for dx, dy in ((-1, 0), (1, 0), (0, -1), (0, 1),
                       (-1, -1), (1, -1), (-1, 1), (1, 1)):
            self.window.blit(outline,
                             outline.get_rect(center=(center[0] + dx,
                                                      center[1] + dy)))
        self.window.blit(txt, txt.get_rect(center=center))

    def _draw_surface_skin(self, tile, corners, scx, scy, sz):
        """Blit cached cosmetic surface art (and emblem) for owned lands."""
        key = self._owner_style_key(tile, 'surface_key')
        if not key or key == 'surface_plain':
            return
        sz_int = max(8, int(sz))
        art = hex_cosmetics.render_surface_art(key, sz_int)
        if art is None:
            return
        self.window.blit(art, (int(scx) - sz_int, int(scy) - sz_int))
        emblem = hex_cosmetics.render_center_emblem(key, sz_int)
        if emblem is not None:
            erect = emblem.get_rect(center=(int(scx), int(scy)))
            self.window.blit(emblem, erect)

    def _draw_owner_border(self, tile, corners):
        """Draw cosmetic kingdom borders without overpainting neighbours.

        Per-edge drawing dispatches to the skin's ``style`` so each border
        cosmetic has a distinct *structural* identity (rope braid, carved
        notches, spikes, gem cabochons, dashed double-line, thorned vine).
        Same-owner internal edges are skipped, and edges shared with another
        visible land are drawn inset toward the hex centre so two adjacent
        kingdoms' borders meet cleanly without overpainting.
        """
        key = self._owner_style_key(tile, 'border_key')
        skin = settings.HEX_BORDER_SKINS.get(
            key, settings.HEX_BORDER_SKINS.get('border_simple_gold', {}))
        style = skin.get('style', 'simple')
        width_bonus = int(skin.get('width_bonus', 0) or 0)
        outer_w = max(1, int((self._border_w + 4 + width_bonus) * self.zoom / 1.0))
        main_w = max(1, int((self._border_w + 2 + width_bonus) * self.zoom / 1.0))
        inner_w = max(1, int(self._border_w * self.zoom / 1.0))
        outer_clr = skin.get('outer', settings.HEX_MINE_BORDER_OUTER)
        main_clr = skin.get('main', settings.HEX_MINE_BORDER)
        highlight_clr = skin.get('highlight', settings.HEX_MINE_BORDER_HIGHLIGHT)
        palette = (outer_clr, main_clr, highlight_clr)
        center_x = sum(x for x, _y in corners) / len(corners)
        center_y = sum(y for _x, y in corners) / len(corners)
        edge_neighbours = _edge_neighbour_coords(tile.col, tile.row)
        external_edges = []
        shared_edges = []
        drawn_vertex_indices = set()
        for edge_idx, coord in enumerate(edge_neighbours):
            start = corners[edge_idx]
            end = corners[(edge_idx + 1) % len(corners)]
            if self._same_owner_neighbour(tile, coord):
                continue
            drawn_vertex_indices.add(edge_idx)
            drawn_vertex_indices.add((edge_idx + 1) % len(corners))
            if self._tile_by_coord.get(coord):
                shared_edges.append((start, end))
            else:
                external_edges.append((start, end))

        def _inset_shared_edge(start, end):
            dx = end[0] - start[0]
            dy = end[1] - start[1]
            length = math.hypot(dx, dy)
            if length <= 0:
                return start, end
            ux = dx / length
            uy = dy / length
            mid_x = (start[0] + end[0]) / 2.0
            mid_y = (start[1] + end[1]) / 2.0
            nx = center_x - mid_x
            ny = center_y - mid_y
            n_len = math.hypot(nx, ny) or 1.0
            nx /= n_len
            ny /= n_len
            inset = max(1.0, outer_w * 0.58)
            shorten = max(0.0, outer_w * 0.32)
            return (
                (start[0] + nx * inset + ux * shorten,
                 start[1] + ny * inset + uy * shorten),
                (end[0] + nx * inset - ux * shorten,
                 end[1] + ny * inset - uy * shorten),
            )

        # External edges: full-thickness style drawing.
        for start, end in external_edges:
            self._draw_border_edge(style, start, end, palette,
                                   outer_w, main_w, inner_w)

        # Shared edges (inset, slightly slimmer so two kingdoms fit cleanly).
        shared_outer = max(1, int(outer_w * 0.70))
        shared_main = max(1, int(main_w * 0.66))
        shared_inner = max(1, int(inner_w * 0.62))
        for start, end in shared_edges:
            ist, iend = _inset_shared_edge(start, end)
            self._draw_border_edge(style, ist, iend, palette,
                                   shared_outer, shared_main, shared_inner)

        # Premium polish: vertex ornaments at every drawn corner.
        if (hex_cosmetics.border_rarity(key) in ('rare', 'epic')
                and self.zoom >= 0.7):
            ornament = hex_cosmetics.render_vertex_ornament(
                key, max(10, int(self._size * self.zoom)))
            if ornament is not None:
                for vidx in drawn_vertex_indices:
                    vx, vy = corners[vidx]
                    rect = ornament.get_rect(center=(int(vx), int(vy)))
                    self.window.blit(ornament, rect)

    def _draw_border_edge(self, style, start, end, palette,
                          outer_w, main_w, inner_w):
        """Render a single owned-hex edge in the requested cosmetic style."""
        outer_clr, main_clr, highlight_clr = palette
        if style == 'simple':
            _draw_capped_line(self.window, outer_clr, start, end, outer_w)
            _draw_capped_line(self.window, main_clr, start, end, main_w)
            _draw_capped_line(self.window, highlight_clr, start, end, inner_w)
            return

        dx = end[0] - start[0]
        dy = end[1] - start[1]
        length = math.hypot(dx, dy)
        if length <= 0:
            _draw_capped_line(self.window, main_clr, start, end, main_w)
            return
        ux, uy = dx / length, dy / length
        nx, ny = -uy, ux  # left-perpendicular unit vector

        def at(t, off=0.0):
            return (start[0] + dx * t + nx * off,
                    start[1] + dy * t + ny * off)

        if style == 'rope_braid':
            offset = main_w * 0.55
            strand_w = max(1, int(main_w * 0.55))
            outer_strand_w = max(1, int(outer_w * 0.55))
            tick_w = max(1, int(inner_w * 0.85))
            # Outer dark wash beneath the two strands.
            _draw_capped_line(self.window, outer_clr,
                              at(0, -offset), at(1, -offset), outer_strand_w)
            _draw_capped_line(self.window, outer_clr,
                              at(0, offset), at(1, offset), outer_strand_w)
            _draw_capped_line(self.window, main_clr,
                              at(0, -offset), at(1, -offset), strand_w)
            _draw_capped_line(self.window, main_clr,
                              at(0, offset), at(1, offset), strand_w)
            # 5 alternating diagonal ticks simulating the braid.
            ticks = 5
            for i in range(ticks):
                t1 = (i + 0.15) / ticks
                t2 = (i + 0.85) / ticks
                if i % 2 == 0:
                    a, b = at(t1, -offset), at(t2, offset)
                else:
                    a, b = at(t1, offset), at(t2, -offset)
                _draw_capped_line(self.window, highlight_clr, a, b, tick_w)
            return

        if style == 'dashed_double':
            offset = main_w * 0.55
            dash_w = max(1, int(main_w * 0.55))
            outer_dash_w = max(1, int(outer_w * 0.55))
            dashes = 6
            for i in range(dashes):
                t1 = (i + 0.05) / dashes
                t2 = (i + 0.65) / dashes
                _draw_capped_line(self.window, outer_clr,
                                  at(t1, -offset), at(t2, -offset), outer_dash_w)
                _draw_capped_line(self.window, outer_clr,
                                  at(t1, offset), at(t2, offset), outer_dash_w)
                _draw_capped_line(self.window, main_clr,
                                  at(t1, -offset), at(t2, -offset), dash_w)
                _draw_capped_line(self.window, main_clr,
                                  at(t1, offset), at(t2, offset), dash_w)
            return

        if style == 'carved_notches':
            # Single thick line interrupted by inward notches.
            _draw_capped_line(self.window, outer_clr, start, end, outer_w)
            _draw_capped_line(self.window, main_clr, start, end, main_w)
            notch_depth = main_w * 0.55
            notch_w = max(1, int(main_w * 0.40))
            for t in (0.18, 0.36, 0.54, 0.72, 0.90):
                p1 = at(t)
                p2 = at(t, notch_depth)
                _draw_capped_line(self.window, outer_clr, p1, p2, notch_w)
            _draw_capped_line(self.window, highlight_clr,
                              at(0, -inner_w * 0.30),
                              at(1, -inner_w * 0.30), max(1, inner_w))
            return

        if style == 'spikes':
            # Zig-zag main line: alternates above/below the edge axis.
            steps = 8
            amp = main_w * 0.65
            polyline = [start]
            for i in range(1, steps):
                t = i / steps
                off = amp if i % 2 == 1 else -amp
                polyline.append(at(t, off))
            polyline.append(end)
            for i in range(len(polyline) - 1):
                _draw_capped_line(self.window, outer_clr,
                                  polyline[i], polyline[i + 1], outer_w)
            for i in range(len(polyline) - 1):
                _draw_capped_line(self.window, main_clr,
                                  polyline[i], polyline[i + 1], main_w)
            for i in range(len(polyline) - 1):
                _draw_capped_line(self.window, highlight_clr,
                                  polyline[i], polyline[i + 1], inner_w)
            return

        if style == 'gem_cabochons':
            # Thick metal bar with 3 gem cabochons inset.
            _draw_capped_line(self.window, outer_clr, start, end, outer_w)
            _draw_capped_line(self.window, main_clr, start, end, main_w)
            _draw_capped_line(self.window, highlight_clr,
                              at(0, -main_w * 0.30),
                              at(1, -main_w * 0.30), max(1, inner_w))
            gem_r = max(2, int(main_w * 0.85))
            for t in (0.25, 0.50, 0.75):
                cx, cy = at(t)
                pygame.draw.circle(self.window, outer_clr,
                                   (int(round(cx)), int(round(cy))), gem_r + 2)
                pygame.draw.circle(self.window, main_clr,
                                   (int(round(cx)), int(round(cy))), gem_r)
                hx = cx + nx * gem_r * 0.30 - ux * gem_r * 0.15
                hy = cy + ny * gem_r * 0.30 - uy * gem_r * 0.15
                pygame.draw.circle(self.window, highlight_clr,
                                   (int(round(hx)), int(round(hy))),
                                   max(1, gem_r // 3))
            return

        if style == 'thorned_vine':
            _draw_capped_line(self.window, outer_clr, start, end, outer_w)
            _draw_capped_line(self.window, main_clr, start, end, main_w)
            thorn_h = main_w * 1.2
            thorn_half = main_w * 0.35
            for t in (0.18, 0.36, 0.54, 0.72, 0.90):
                base_pt = at(t)
                left = at(t - 0.04)
                right = at(t + 0.04)
                tip = at(t, -thorn_h)
                pygame.draw.polygon(self.window, outer_clr, [
                    (int(round(left[0])), int(round(left[1]))),
                    (int(round(right[0])), int(round(right[1]))),
                    (int(round(tip[0])), int(round(tip[1]))),
                ])
                # Thin inner highlight on the thorn.
                pygame.draw.line(self.window, highlight_clr,
                                 (int(round(base_pt[0])), int(round(base_pt[1]))),
                                 (int(round(tip[0])), int(round(tip[1]))),
                                 max(1, int(thorn_half)))
            return

        # Unknown style → simple fallback.
        _draw_capped_line(self.window, outer_clr, start, end, outer_w)
        _draw_capped_line(self.window, main_clr, start, end, main_w)
        _draw_capped_line(self.window, highlight_clr, start, end, inner_w)

    def _draw_tier_stars(self, cx, cy, tier, sz):
        """Draw one star per tier level."""
        max_count = len(getattr(settings, 'TIER_LABELS', {1: '', 2: '', 3: ''})) or 4
        count = max(1, min(max_count, int(tier or 1)))
        outer = max(4, int(sz * 0.112))
        inner = max(2, int(outer * 0.50))
        gap = max(2, int(outer * 0.56))
        total_w = count * outer * 2 + (count - 1) * gap
        start_x = cx - total_w / 2 + outer
        outline_w = 2 if outer >= 7 else 1
        for i in range(count):
            sx = start_x + i * (outer * 2 + gap)
            shadow = _star_points(sx + 1, cy + 1, outer, inner)
            pts = _star_points(sx, cy, outer, inner)
            pygame.draw.polygon(self.window, (36, 24, 8), shadow)
            pygame.draw.polygon(self.window, settings.HEX_STAR_FILL, pts)
            pygame.draw.polygon(self.window, settings.HEX_STAR_BORDER, pts, outline_w)

    # ── Minimap ─────────────────────────────────────────────────────

    def _draw_minimap(self):
        """Draw a small overview map in the bottom-right corner."""
        if not self.tiles:
            return

        mm_w = settings.MINIMAP_W
        mm_h = settings.MINIMAP_H
        margin = settings.MINIMAP_MARGIN
        if hasattr(self, 'minimap_origin') and self.minimap_origin:
            mm_x, mm_y = self.minimap_origin
        else:
            mm_x = settings.SCREEN_WIDTH - mm_w - margin
            mm_y = settings.SCREEN_HEIGHT - mm_h - margin

        # Background
        mm_surf = pygame.Surface((mm_w, mm_h), pygame.SRCALPHA)
        mm_surf.fill(settings.MINIMAP_BG_CLR)

        # Compute world bounds
        min_wx = min(t.cx for t in self.tiles) - self._size
        max_wx = max(t.cx for t in self.tiles) + self._size
        min_wy = min(t.cy for t in self.tiles) - self._size
        max_wy = max(t.cy for t in self.tiles) + self._size
        world_w = max_wx - min_wx
        world_h = max_wy - min_wy
        if world_w == 0 or world_h == 0:
            return

        scale = min((mm_w - 8) / world_w, (mm_h - 8) / world_h)
        off_x = (mm_w - world_w * scale) / 2
        off_y = (mm_h - world_h * scale) / 2

        # Draw hex dots
        for tile in self.tiles:
            tx = off_x + (tile.cx - min_wx) * scale
            ty = off_y + (tile.cy - min_wy) * scale
            dot_r = max(2, int(self._size * scale * 0.5))
            clr = _tile_fill_color(tile)
            border = _tile_border_color(tile)
            if tile.is_mine:
                pygame.draw.circle(mm_surf, settings.HEX_MINE_BORDER,
                                   (int(tx), int(ty)), dot_r + 2)
                border = (255, 245, 190)
            pygame.draw.circle(mm_surf, clr, (int(tx), int(ty)), dot_r)
            pygame.draw.circle(mm_surf, border, (int(tx), int(ty)), dot_r, 1)

        # Draw viewport rectangle
        vp_left = off_x + (self.camera_x - min_wx) * scale
        vp_top = off_y + (self.camera_y - min_wy) * scale
        vp_w = self.viewport_rect.w / self.zoom * scale
        vp_h = self.viewport_rect.h / self.zoom * scale
        vp_rect = pygame.Rect(int(vp_left), int(vp_top), int(vp_w), int(vp_h))
        pygame.draw.rect(mm_surf, settings.MINIMAP_VIEWPORT_CLR, vp_rect, 1)

        # Border
        pygame.draw.rect(mm_surf, settings.MINIMAP_BORDER_CLR,
                         mm_surf.get_rect(), settings.MINIMAP_BORDER_W)

        self.window.blit(mm_surf, (mm_x, mm_y))
        self._minimap_rect = pygame.Rect(mm_x, mm_y, mm_w, mm_h)
        # Store minimap transform info for click handling
        self._mm_scale = scale
        self._mm_off_x = off_x
        self._mm_off_y = off_y
        self._mm_min_wx = min_wx
        self._mm_min_wy = min_wy
        self._mm_x = mm_x
        self._mm_y = mm_y

    def focus_land(self, land_id):
        """Select and centre the map on a land id. Returns the tile if found."""
        for tile in self.tiles:
            if tile.land_id == land_id:
                self.selected_tile = tile
                self.camera_x = tile.cx - self.viewport_rect.w / (2 * self.zoom)
                self.camera_y = tile.cy - self.viewport_rect.h / (2 * self.zoom)
                self._clamp_camera()
                return tile
        return None

    def focus_lands(self, land_ids):
        """Centre the camera on a set of land IDs. Returns selected tile or None."""
        if not land_ids:
            return None

        wanted = {land_id for land_id in land_ids if land_id is not None}
        if not wanted:
            return None

        targets = [tile for tile in self.tiles if tile.land_id in wanted]
        if not targets:
            return None

        center_x = sum(tile.cx for tile in targets) / len(targets)
        center_y = sum(tile.cy for tile in targets) / len(targets)
        self.camera_x = center_x - self.viewport_rect.w / (2 * self.zoom)
        self.camera_y = center_y - self.viewport_rect.h / (2 * self.zoom)
        self._clamp_camera()

        selected = min(
            targets,
            key=lambda tile: (
                (tile.cx - center_x) ** 2 + (tile.cy - center_y) ** 2,
                tile.land_id,
            ),
        )
        self.selected_tile = selected
        return selected

    def handle_minimap_click(self, sx, sy):
        """If (sx, sy) is inside the minimap, jump camera there. Returns True if handled."""
        if not hasattr(self, '_minimap_rect') or not self._minimap_rect.collidepoint(sx, sy):
            return False
        # Convert minimap pixel to world coordinate
        local_x = sx - self._mm_x
        local_y = sy - self._mm_y
        wx = (local_x - self._mm_off_x) / self._mm_scale + self._mm_min_wx
        wy = (local_y - self._mm_off_y) / self._mm_scale + self._mm_min_wy
        # Centre camera on that world point
        self.camera_x = wx - self.viewport_rect.w / (2 * self.zoom)
        self.camera_y = wy - self.viewport_rect.h / (2 * self.zoom)
        self._clamp_camera()
        return True

    def update_data(self, lands_data):
        """Refresh tile data (e.g. after ownership change) without resetting camera."""
        old_cam = (self.camera_x, self.camera_y, self.zoom)
        self._build_tiles(lands_data)
        self.camera_x, self.camera_y, self.zoom = old_cam
        self.selected_tile = None
        self.hovered_tile = None
